// GENERATED by tools/srd/generate.mjs from the 5e-bits SRD 5.1 database (MIT). Do not edit by hand; change the generator and run it again.
import { dice, flat } from "../../../dice/dice-expression.js";
import { defineArmor, defineWeapon, type ItemDefinition } from "../../../rules/content-definitions.js";

const source = "SRD 5.1";
const melee = { kind: "melee" } as const;

export const handaxe = defineWeapon({ id: "item:handaxe", source, damage: dice(1, 6), damageType: "slashing", range: melee, finesse: false, natural: false });
export const lightHammer = defineWeapon({ id: "item:light-hammer", source, damage: dice(1, 4), damageType: "bludgeoning", range: melee, finesse: false, natural: false });
export const sickle = defineWeapon({ id: "item:sickle", source, damage: dice(1, 4), damageType: "slashing", range: melee, finesse: false, natural: false });
export const dart = defineWeapon({ id: "item:dart", source, damage: dice(1, 4), damageType: "piercing", range: { kind: "ranged", normal: 20, long: 60 }, finesse: true, natural: false });
export const sling = defineWeapon({ id: "item:sling", source, damage: dice(1, 4), damageType: "bludgeoning", range: { kind: "ranged", normal: 30, long: 120 }, finesse: false, natural: false });
export const battleaxe = defineWeapon({ id: "item:battleaxe", source, damage: dice(1, 8), damageType: "slashing", range: melee, finesse: false, natural: false });
export const flail = defineWeapon({ id: "item:flail", source, damage: dice(1, 8), damageType: "bludgeoning", range: melee, finesse: false, natural: false });
export const glaive = defineWeapon({ id: "item:glaive", source, damage: dice(1, 10), damageType: "slashing", range: melee, finesse: false, natural: false });
export const greatsword = defineWeapon({ id: "item:greatsword", source, damage: dice(2, 6), damageType: "slashing", range: melee, finesse: false, natural: false });
export const halberd = defineWeapon({ id: "item:halberd", source, damage: dice(1, 10), damageType: "slashing", range: melee, finesse: false, natural: false });
export const lance = defineWeapon({ id: "item:lance", source, damage: dice(1, 12), damageType: "piercing", range: melee, finesse: false, natural: false });
export const maul = defineWeapon({ id: "item:maul", source, damage: dice(2, 6), damageType: "bludgeoning", range: melee, finesse: false, natural: false });
export const pike = defineWeapon({ id: "item:pike", source, damage: dice(1, 10), damageType: "piercing", range: melee, finesse: false, natural: false });
export const trident = defineWeapon({ id: "item:trident", source, damage: dice(1, 6), damageType: "piercing", range: melee, finesse: false, natural: false });
export const warPick = defineWeapon({ id: "item:war-pick", source, damage: dice(1, 8), damageType: "piercing", range: melee, finesse: false, natural: false });
export const warhammer = defineWeapon({ id: "item:warhammer", source, damage: dice(1, 8), damageType: "bludgeoning", range: melee, finesse: false, natural: false });
export const whip = defineWeapon({ id: "item:whip", source, damage: dice(1, 4), damageType: "slashing", range: melee, finesse: true, natural: false });
export const blowgun = defineWeapon({ id: "item:blowgun", source, damage: flat(1), damageType: "piercing", range: { kind: "ranged", normal: 25, long: 100 }, finesse: false, natural: false });
export const handCrossbow = defineWeapon({ id: "item:hand-crossbow", source, damage: dice(1, 6), damageType: "piercing", range: { kind: "ranged", normal: 30, long: 120 }, finesse: false, natural: false });
export const heavyCrossbow = defineWeapon({ id: "item:heavy-crossbow", source, damage: dice(1, 10), damageType: "piercing", range: { kind: "ranged", normal: 100, long: 400 }, finesse: false, natural: false });
export const paddedArmor = defineArmor({ id: "item:padded-armor", source, category: "light", baseArmorClass: 11, dexterityCap: null, stealthDisadvantage: true, strengthRequirement: null });
export const studdedLeatherArmor = defineArmor({ id: "item:studded-leather-armor", source, category: "light", baseArmorClass: 12, dexterityCap: null, stealthDisadvantage: false, strengthRequirement: null });
export const chainShirt = defineArmor({ id: "item:chain-shirt", source, category: "medium", baseArmorClass: 13, dexterityCap: 2, stealthDisadvantage: false, strengthRequirement: null });
export const scaleMail = defineArmor({ id: "item:scale-mail", source, category: "medium", baseArmorClass: 14, dexterityCap: 2, stealthDisadvantage: true, strengthRequirement: null });
export const breastplate = defineArmor({ id: "item:breastplate", source, category: "medium", baseArmorClass: 14, dexterityCap: 2, stealthDisadvantage: false, strengthRequirement: null });
export const halfPlateArmor = defineArmor({ id: "item:half-plate-armor", source, category: "medium", baseArmorClass: 15, dexterityCap: 2, stealthDisadvantage: true, strengthRequirement: null });
export const ringMail = defineArmor({ id: "item:ring-mail", source, category: "heavy", baseArmorClass: 14, dexterityCap: 0, stealthDisadvantage: true, strengthRequirement: null });
export const splintArmor = defineArmor({ id: "item:splint-armor", source, category: "heavy", baseArmorClass: 17, dexterityCap: 0, stealthDisadvantage: true, strengthRequirement: 15 });
export const plateArmor = defineArmor({ id: "item:plate-armor", source, category: "heavy", baseArmorClass: 18, dexterityCap: 0, stealthDisadvantage: true, strengthRequirement: 15 });

// What generated monsters bite, claw and slam with. The damage die here is a
// placeholder: each monster's attack carries its own damage.
export const tentacle = defineWeapon({ id: "item:tentacle", source, damage: dice(1, 6), damageType: "bludgeoning", range: melee, finesse: false, natural: true });
export const tail = defineWeapon({ id: "item:tail", source, damage: dice(1, 6), damageType: "bludgeoning", range: melee, finesse: false, natural: true });
export const biteSlashing = defineWeapon({ id: "item:bite-slashing", source, damage: dice(1, 6), damageType: "slashing", range: melee, finesse: false, natural: true });
export const fist = defineWeapon({ id: "item:fist", source, damage: dice(1, 6), damageType: "bludgeoning", range: melee, finesse: false, natural: true });
export const rock = defineWeapon({ id: "item:rock", source, damage: dice(1, 6), damageType: "bludgeoning", range: { kind: "ranged", normal: 25, long: 50 }, finesse: false, natural: true });
export const rake = defineWeapon({ id: "item:rake", source, damage: dice(1, 6), damageType: "slashing", range: melee, finesse: false, natural: true });
export const beak = defineWeapon({ id: "item:beak", source, damage: dice(1, 6), damageType: "slashing", range: melee, finesse: false, natural: true });
export const clawPiercing = defineWeapon({ id: "item:claw-piercing", source, damage: dice(1, 6), damageType: "piercing", range: melee, finesse: false, natural: true });
export const tailPiercing = defineWeapon({ id: "item:tail-piercing", source, damage: dice(1, 6), damageType: "piercing", range: melee, finesse: false, natural: true });
export const hurlFlame = defineWeapon({ id: "item:hurl-flame", source, damage: dice(1, 6), damageType: "fire", range: melee, finesse: false, natural: true });
export const beard = defineWeapon({ id: "item:beard", source, damage: dice(1, 6), damageType: "piercing", range: melee, finesse: false, natural: true });
export const constrict = defineWeapon({ id: "item:constrict", source, damage: dice(1, 6), damageType: "bludgeoning", range: melee, finesse: false, natural: true });
export const pseudopod = defineWeapon({ id: "item:pseudopod", source, damage: dice(1, 6), damageType: "bludgeoning", range: melee, finesse: false, natural: true });
export const beakPiercing = defineWeapon({ id: "item:beak-piercing", source, damage: dice(1, 6), damageType: "piercing", range: melee, finesse: false, natural: true });
export const sting = defineWeapon({ id: "item:sting", source, damage: dice(1, 6), damageType: "piercing", range: melee, finesse: false, natural: true });
export const biteBludgeoning = defineWeapon({ id: "item:bite-bludgeoning", source, damage: dice(1, 6), damageType: "bludgeoning", range: melee, finesse: false, natural: true });
export const claws = defineWeapon({ id: "item:claws", source, damage: dice(1, 6), damageType: "slashing", range: melee, finesse: false, natural: true });
export const hooves = defineWeapon({ id: "item:hooves", source, damage: dice(1, 6), damageType: "bludgeoning", range: melee, finesse: false, natural: true });
export const chain = defineWeapon({ id: "item:chain", source, damage: dice(1, 6), damageType: "slashing", range: melee, finesse: false, natural: true });
export const horns = defineWeapon({ id: "item:horns", source, damage: dice(1, 6), damageType: "bludgeoning", range: melee, finesse: false, natural: true });
export const pincer = defineWeapon({ id: "item:pincer", source, damage: dice(1, 6), damageType: "bludgeoning", range: melee, finesse: false, natural: true });
export const tailSlashing = defineWeapon({ id: "item:tail-slashing", source, damage: dice(1, 6), damageType: "slashing", range: melee, finesse: false, natural: true });
export const clawBludgeoning = defineWeapon({ id: "item:claw-bludgeoning", source, damage: dice(1, 6), damageType: "bludgeoning", range: melee, finesse: false, natural: true });
export const crush = defineWeapon({ id: "item:crush", source, damage: dice(1, 6), damageType: "bludgeoning", range: melee, finesse: false, natural: true });
export const poisonedDart = defineWeapon({ id: "item:poisoned-dart", source, damage: dice(1, 6), damageType: "piercing", range: { kind: "ranged", normal: 30, long: 120 }, finesse: false, natural: true });
export const talons = defineWeapon({ id: "item:talons", source, damage: dice(1, 6), damageType: "slashing", range: melee, finesse: false, natural: true });
export const gore = defineWeapon({ id: "item:gore", source, damage: dice(1, 6), damageType: "piercing", range: melee, finesse: false, natural: true });
export const stomp = defineWeapon({ id: "item:stomp", source, damage: dice(1, 6), damageType: "bludgeoning", range: melee, finesse: false, natural: true });
export const ram = defineWeapon({ id: "item:ram", source, damage: dice(1, 6), damageType: "bludgeoning", range: melee, finesse: false, natural: true });
export const touch = defineWeapon({ id: "item:touch", source, damage: dice(1, 6), damageType: "fire", range: melee, finesse: false, natural: true });
export const pseudopodAcid = defineWeapon({ id: "item:pseudopod-acid", source, damage: dice(1, 6), damageType: "acid", range: melee, finesse: false, natural: true });
export const witheringTouch = defineWeapon({ id: "item:withering-touch", source, damage: dice(1, 6), damageType: "necrotic", range: melee, finesse: false, natural: true });
export const tentacles = defineWeapon({ id: "item:tentacles", source, damage: dice(1, 6), damageType: "bludgeoning", range: melee, finesse: false, natural: true });
export const bites = defineWeapon({ id: "item:bites", source, damage: dice(1, 6), damageType: "piercing", range: melee, finesse: false, natural: true });
export const shieldBash = defineWeapon({ id: "item:shield-bash", source, damage: dice(1, 6), damageType: "bludgeoning", range: melee, finesse: false, natural: true });
export const tentaclesSlashing = defineWeapon({ id: "item:tentacles-slashing", source, damage: dice(1, 6), damageType: "slashing", range: melee, finesse: false, natural: true });
export const spikedBoneClub = defineWeapon({ id: "item:spiked-bone-club", source, damage: dice(1, 6), damageType: "bludgeoning", range: melee, finesse: false, natural: true });
export const fork = defineWeapon({ id: "item:fork", source, damage: dice(1, 6), damageType: "piercing", range: melee, finesse: false, natural: true });
export const sword = defineWeapon({ id: "item:sword", source, damage: dice(1, 6), damageType: "slashing", range: melee, finesse: false, natural: true });
export const paralyzingTouch = defineWeapon({ id: "item:paralyzing-touch", source, damage: dice(1, 6), damageType: "cold", range: melee, finesse: false, natural: true });
export const tailSpike = defineWeapon({ id: "item:tail-spike", source, damage: dice(1, 6), damageType: "piercing", range: { kind: "ranged", normal: 100, long: 200 }, finesse: false, natural: true });
export const snakeHair = defineWeapon({ id: "item:snake-hair", source, damage: dice(1, 6), damageType: "piercing", range: melee, finesse: false, natural: true });
export const harpoon = defineWeapon({ id: "item:harpoon", source, damage: dice(1, 6), damageType: "piercing", range: { kind: "ranged", normal: 20, long: 60 }, finesse: false, natural: true });
export const rottingFist = defineWeapon({ id: "item:rotting-fist", source, damage: dice(1, 6), damageType: "bludgeoning", range: melee, finesse: false, natural: true });
export const tailStinger = defineWeapon({ id: "item:tail-stinger", source, damage: dice(1, 6), damageType: "piercing", range: melee, finesse: false, natural: true });
export const goreBludgeoning = defineWeapon({ id: "item:gore-bludgeoning", source, damage: dice(1, 6), damageType: "bludgeoning", range: melee, finesse: false, natural: true });
export const strengthDrain = defineWeapon({ id: "item:strength-drain", source, damage: dice(1, 6), damageType: "necrotic", range: melee, finesse: false, natural: true });
export const slayingLongbow = defineWeapon({ id: "item:slaying-longbow", source, damage: dice(1, 6), damageType: "piercing", range: { kind: "ranged", normal: 150, long: 600 }, finesse: false, natural: true });
export const bloodDrain = defineWeapon({ id: "item:blood-drain", source, damage: dice(1, 6), damageType: "piercing", range: melee, finesse: false, natural: true });
export const beaks = defineWeapon({ id: "item:beaks", source, damage: dice(1, 6), damageType: "piercing", range: melee, finesse: false, natural: true });
export const hornsPiercing = defineWeapon({ id: "item:horns-piercing", source, damage: dice(1, 6), damageType: "piercing", range: melee, finesse: false, natural: true });
export const horn = defineWeapon({ id: "item:horn", source, damage: dice(1, 6), damageType: "piercing", range: melee, finesse: false, natural: true });
export const unarmedStrike = defineWeapon({ id: "item:unarmed-strike", source, damage: dice(1, 6), damageType: "bludgeoning", range: melee, finesse: false, natural: true });
export const rottingTouch = defineWeapon({ id: "item:rotting-touch", source, damage: dice(1, 6), damageType: "necrotic", range: melee, finesse: false, natural: true });
export const tusks = defineWeapon({ id: "item:tusks", source, damage: dice(1, 6), damageType: "slashing", range: melee, finesse: false, natural: true });
export const shock = defineWeapon({ id: "item:shock", source, damage: dice(1, 6), damageType: "lightning", range: melee, finesse: false, natural: true });
export const stinger = defineWeapon({ id: "item:stinger", source, damage: dice(1, 6), damageType: "piercing", range: melee, finesse: false, natural: true });

export const srd51GeneratedItems: readonly ItemDefinition[] = [
  handaxe,
  lightHammer,
  sickle,
  dart,
  sling,
  battleaxe,
  flail,
  glaive,
  greatsword,
  halberd,
  lance,
  maul,
  pike,
  trident,
  warPick,
  warhammer,
  whip,
  blowgun,
  handCrossbow,
  heavyCrossbow,
  paddedArmor,
  studdedLeatherArmor,
  chainShirt,
  scaleMail,
  breastplate,
  halfPlateArmor,
  ringMail,
  splintArmor,
  plateArmor,
  tentacle,
  tail,
  biteSlashing,
  fist,
  rock,
  rake,
  beak,
  clawPiercing,
  tailPiercing,
  hurlFlame,
  beard,
  constrict,
  pseudopod,
  beakPiercing,
  sting,
  biteBludgeoning,
  claws,
  hooves,
  chain,
  horns,
  pincer,
  tailSlashing,
  clawBludgeoning,
  crush,
  poisonedDart,
  talons,
  gore,
  stomp,
  ram,
  touch,
  pseudopodAcid,
  witheringTouch,
  tentacles,
  bites,
  shieldBash,
  tentaclesSlashing,
  spikedBoneClub,
  fork,
  sword,
  paralyzingTouch,
  tailSpike,
  snakeHair,
  harpoon,
  rottingFist,
  tailStinger,
  goreBludgeoning,
  strengthDrain,
  slayingLongbow,
  bloodDrain,
  beaks,
  hornsPiercing,
  horn,
  unarmedStrike,
  rottingTouch,
  tusks,
  shock,
  stinger,
];
