// GENERATED by tools/srd/generate.mjs from the 5e-bits SRD 5.1 database (MIT). Do not edit by hand; change the generator and run it again.
import { dice, flat } from "../../../dice/dice-expression.js";
import { defineArmor, defineGear, defineWeapon, type ItemDefinition } from "../../../rules/content-definitions.js";

const source = "SRD 5.1";
const melee = { kind: "melee" } as const;

export const handaxe = defineWeapon({ id: "item:handaxe", source, damage: dice(1, 6), damageType: "slashing", range: melee, finesse: false, light: true, natural: false });
export const lightHammer = defineWeapon({ id: "item:light-hammer", source, damage: dice(1, 4), damageType: "bludgeoning", range: melee, finesse: false, light: true, natural: false });
export const sickle = defineWeapon({ id: "item:sickle", source, damage: dice(1, 4), damageType: "slashing", range: melee, finesse: false, light: true, natural: false });
export const dart = defineWeapon({ id: "item:dart", source, damage: dice(1, 4), damageType: "piercing", range: { kind: "ranged", normal: 20, long: 60 }, finesse: true, natural: false });
export const sling = defineWeapon({ id: "item:sling", source, damage: dice(1, 4), damageType: "bludgeoning", range: { kind: "ranged", normal: 30, long: 120 }, finesse: false, natural: false });
export const battleaxe = defineWeapon({ id: "item:battleaxe", source, damage: dice(1, 8), damageType: "slashing", range: melee, finesse: false, natural: false });
export const flail = defineWeapon({ id: "item:flail", source, damage: dice(1, 8), damageType: "bludgeoning", range: melee, finesse: false, natural: false });
export const glaive = defineWeapon({ id: "item:glaive", source, damage: dice(1, 10), damageType: "slashing", range: melee, finesse: false, natural: false });
export const greatsword = defineWeapon({ id: "item:greatsword", source, damage: dice(2, 6), damageType: "slashing", range: melee, finesse: false, natural: false });
export const halberd = defineWeapon({ id: "item:halberd", source, damage: dice(1, 10), damageType: "slashing", range: melee, finesse: false, natural: false });
export const lance = defineWeapon({ id: "item:lance", source, damage: dice(1, 12), damageType: "piercing", range: melee, finesse: false, natural: false });
export const maul = defineWeapon({ id: "item:maul", source, damage: dice(2, 6), damageType: "bludgeoning", range: melee, finesse: false, natural: false });
export const pike = defineWeapon({ id: "item:pike", source, damage: dice(1, 10), damageType: "piercing", range: melee, finesse: false, natural: false });
export const trident = defineWeapon({ id: "item:trident", source, damage: dice(1, 6), damageType: "piercing", range: melee, finesse: false, natural: false });
export const warPick = defineWeapon({ id: "item:war-pick", source, damage: dice(1, 8), damageType: "piercing", range: melee, finesse: false, natural: false });
export const warhammer = defineWeapon({ id: "item:warhammer", source, damage: dice(1, 8), damageType: "bludgeoning", range: melee, finesse: false, natural: false });
export const whip = defineWeapon({ id: "item:whip", source, damage: dice(1, 4), damageType: "slashing", range: melee, finesse: true, natural: false });
export const blowgun = defineWeapon({ id: "item:blowgun", source, damage: flat(1), damageType: "piercing", range: { kind: "ranged", normal: 25, long: 100 }, finesse: false, natural: false });
export const handCrossbow = defineWeapon({ id: "item:hand-crossbow", source, damage: dice(1, 6), damageType: "piercing", range: { kind: "ranged", normal: 30, long: 120 }, finesse: false, light: true, natural: false });
export const heavyCrossbow = defineWeapon({ id: "item:heavy-crossbow", source, damage: dice(1, 10), damageType: "piercing", range: { kind: "ranged", normal: 100, long: 400 }, finesse: false, natural: false });
export const paddedArmor = defineArmor({ id: "item:padded-armor", source, category: "light", baseArmorClass: 11, dexterityCap: null, stealthDisadvantage: true, strengthRequirement: null });
export const studdedLeatherArmor = defineArmor({ id: "item:studded-leather-armor", source, category: "light", baseArmorClass: 12, dexterityCap: null, stealthDisadvantage: false, strengthRequirement: null });
export const chainShirt = defineArmor({ id: "item:chain-shirt", source, category: "medium", baseArmorClass: 13, dexterityCap: 2, stealthDisadvantage: false, strengthRequirement: null });
export const scaleMail = defineArmor({ id: "item:scale-mail", source, category: "medium", baseArmorClass: 14, dexterityCap: 2, stealthDisadvantage: true, strengthRequirement: null });
export const breastplate = defineArmor({ id: "item:breastplate", source, category: "medium", baseArmorClass: 14, dexterityCap: 2, stealthDisadvantage: false, strengthRequirement: null });
export const halfPlateArmor = defineArmor({ id: "item:half-plate-armor", source, category: "medium", baseArmorClass: 15, dexterityCap: 2, stealthDisadvantage: true, strengthRequirement: null });
export const ringMail = defineArmor({ id: "item:ring-mail", source, category: "heavy", baseArmorClass: 14, dexterityCap: 0, stealthDisadvantage: true, strengthRequirement: null });
export const splintArmor = defineArmor({ id: "item:splint-armor", source, category: "heavy", baseArmorClass: 17, dexterityCap: 0, stealthDisadvantage: true, strengthRequirement: 15 });
export const plateArmor = defineArmor({ id: "item:plate-armor", source, category: "heavy", baseArmorClass: 18, dexterityCap: 0, stealthDisadvantage: true, strengthRequirement: 15 });

// Adventuring gear, tools, mounts and vehicles: named, priced and weighed.
export const abacus = defineGear({ id: "item:abacus", source, category: "gear", costCp: 200, weight: 2 });
export const acidVial = defineGear({ id: "item:acid-vial", source, category: "gear", costCp: 2500, weight: 1 });
export const alchemistsFireFlask = defineGear({ id: "item:alchemists-fire-flask", source, category: "gear", costCp: 5000, weight: 1 });
export const almsBox = defineGear({ id: "item:alms-box", source, category: "gear", costCp: 0, weight: 0 });
export const arrow = defineGear({ id: "item:arrow", source, category: "gear", costCp: 100, weight: 1 });
export const blockOfIncense = defineGear({ id: "item:block-of-incense", source, category: "gear", costCp: 0, weight: 0 });
export const blowgunNeedle = defineGear({ id: "item:blowgun-needle", source, category: "gear", costCp: 100, weight: 1 });
export const censer = defineGear({ id: "item:censer", source, category: "gear", costCp: 0, weight: 0 });
export const crossbowBolt = defineGear({ id: "item:crossbow-bolt", source, category: "gear", costCp: 100, weight: 1.5 });
export const slingBullet = defineGear({ id: "item:sling-bullet", source, category: "gear", costCp: 4, weight: 1.5 });
export const amulet = defineGear({ id: "item:amulet", source, category: "gear", costCp: 500, weight: 1 });
export const antitoxinVial = defineGear({ id: "item:antitoxin-vial", source, category: "gear", costCp: 5000, weight: 0 });
export const crystal = defineGear({ id: "item:crystal", source, category: "gear", costCp: 1000, weight: 1 });
export const orb = defineGear({ id: "item:orb", source, category: "gear", costCp: 2000, weight: 3 });
export const rod = defineGear({ id: "item:rod", source, category: "gear", costCp: 1000, weight: 2 });
export const staff = defineGear({ id: "item:staff", source, category: "gear", costCp: 500, weight: 4 });
export const wand = defineGear({ id: "item:wand", source, category: "gear", costCp: 1000, weight: 1 });
export const backpack = defineGear({ id: "item:backpack", source, category: "gear", costCp: 200, weight: 5 });
export const ballBearingsBagOf1000 = defineGear({ id: "item:ball-bearings-bag-of-1000", source, category: "gear", costCp: 100, weight: 2 });
export const barrel = defineGear({ id: "item:barrel", source, category: "gear", costCp: 200, weight: 70 });
export const basket = defineGear({ id: "item:basket", source, category: "gear", costCp: 40, weight: 2 });
export const bedroll = defineGear({ id: "item:bedroll", source, category: "gear", costCp: 100, weight: 7 });
export const bell = defineGear({ id: "item:bell", source, category: "gear", costCp: 100, weight: 0 });
export const blanket = defineGear({ id: "item:blanket", source, category: "gear", costCp: 50, weight: 3 });
export const blockAndTackle = defineGear({ id: "item:block-and-tackle", source, category: "gear", costCp: 100, weight: 5 });
export const book = defineGear({ id: "item:book", source, category: "gear", costCp: 2500, weight: 5 });
export const bottleGlass = defineGear({ id: "item:bottle-glass", source, category: "gear", costCp: 200, weight: 2 });
export const bucket = defineGear({ id: "item:bucket", source, category: "gear", costCp: 5, weight: 2 });
export const caltrops = defineGear({ id: "item:caltrops", source, category: "gear", costCp: 5, weight: 2 });
export const candle = defineGear({ id: "item:candle", source, category: "gear", costCp: 1, weight: 0 });
export const caseCrossbowBolt = defineGear({ id: "item:case-crossbow-bolt", source, category: "gear", costCp: 100, weight: 1 });
export const caseMapOrScroll = defineGear({ id: "item:case-map-or-scroll", source, category: "gear", costCp: 100, weight: 1 });
export const chain10Feet = defineGear({ id: "item:chain-10-feet", source, category: "gear", costCp: 500, weight: 10 });
export const chalk1Piece = defineGear({ id: "item:chalk-1-piece", source, category: "gear", costCp: 1, weight: 0 });
export const chest = defineGear({ id: "item:chest", source, category: "gear", costCp: 500, weight: 25 });
export const clothesCommon = defineGear({ id: "item:clothes-common", source, category: "gear", costCp: 50, weight: 3 });
export const clothesCostume = defineGear({ id: "item:clothes-costume", source, category: "gear", costCp: 500, weight: 4 });
export const clothesFine = defineGear({ id: "item:clothes-fine", source, category: "gear", costCp: 1500, weight: 6 });
export const clothesTravelers = defineGear({ id: "item:clothes-travelers", source, category: "gear", costCp: 200, weight: 4 });
export const componentPouch = defineGear({ id: "item:component-pouch", source, category: "gear", costCp: 2500, weight: 2 });
export const crowbar = defineGear({ id: "item:crowbar", source, category: "gear", costCp: 200, weight: 5 });
export const sprigOfMistletoe = defineGear({ id: "item:sprig-of-mistletoe", source, category: "gear", costCp: 100, weight: 0 });
export const totem = defineGear({ id: "item:totem", source, category: "gear", costCp: 100, weight: 0 });
export const woodenStaff = defineGear({ id: "item:wooden-staff", source, category: "gear", costCp: 500, weight: 4 });
export const yewWand = defineGear({ id: "item:yew-wand", source, category: "gear", costCp: 1000, weight: 1 });
export const emblem = defineGear({ id: "item:emblem", source, category: "gear", costCp: 500, weight: 0 });
export const fishingTackle = defineGear({ id: "item:fishing-tackle", source, category: "gear", costCp: 100, weight: 4 });
export const flaskOrTankard = defineGear({ id: "item:flask-or-tankard", source, category: "gear", costCp: 2, weight: 1 });
export const grapplingHook = defineGear({ id: "item:grappling-hook", source, category: "gear", costCp: 200, weight: 4 });
export const hammer = defineGear({ id: "item:hammer", source, category: "gear", costCp: 100, weight: 3 });
export const hammerSledge = defineGear({ id: "item:hammer-sledge", source, category: "gear", costCp: 200, weight: 10 });
export const holyWaterFlask = defineGear({ id: "item:holy-water-flask", source, category: "gear", costCp: 2500, weight: 1 });
export const hourglass = defineGear({ id: "item:hourglass", source, category: "gear", costCp: 2500, weight: 1 });
export const huntingTrap = defineGear({ id: "item:hunting-trap", source, category: "gear", costCp: 500, weight: 25 });
export const ink1OunceBottle = defineGear({ id: "item:ink-1-ounce-bottle", source, category: "gear", costCp: 1000, weight: 0 });
export const inkPen = defineGear({ id: "item:ink-pen", source, category: "gear", costCp: 2, weight: 0 });
export const jugOrPitcher = defineGear({ id: "item:jug-or-pitcher", source, category: "gear", costCp: 2, weight: 4 });
export const climbersKit = defineGear({ id: "item:climbers-kit", source, category: "gear", costCp: 2500, weight: 12 });
export const disguiseKit = defineGear({ id: "item:disguise-kit", source, category: "gear", costCp: 2500, weight: 3 });
export const forgeryKit = defineGear({ id: "item:forgery-kit", source, category: "gear", costCp: 1500, weight: 5 });
export const herbalismKit = defineGear({ id: "item:herbalism-kit", source, category: "gear", costCp: 500, weight: 3 });
export const healersKit = defineGear({ id: "item:healers-kit", source, category: "gear", costCp: 500, weight: 3 });
export const messKit = defineGear({ id: "item:mess-kit", source, category: "gear", costCp: 20, weight: 1 });
export const poisonersKit = defineGear({ id: "item:poisoners-kit", source, category: "gear", costCp: 5000, weight: 2 });
export const ladder10Foot = defineGear({ id: "item:ladder-10-foot", source, category: "gear", costCp: 10, weight: 25 });
export const lamp = defineGear({ id: "item:lamp", source, category: "gear", costCp: 50, weight: 1 });
export const lanternBullseye = defineGear({ id: "item:lantern-bullseye", source, category: "gear", costCp: 1000, weight: 2 });
export const lanternHooded = defineGear({ id: "item:lantern-hooded", source, category: "gear", costCp: 500, weight: 2 });
export const littleBagOfSand = defineGear({ id: "item:little-bag-of-sand", source, category: "gear", costCp: 0, weight: 0 });
export const lock = defineGear({ id: "item:lock", source, category: "gear", costCp: 1000, weight: 1 });
export const magnifyingGlass = defineGear({ id: "item:magnifying-glass", source, category: "gear", costCp: 10000, weight: 0 });
export const manacles = defineGear({ id: "item:manacles", source, category: "gear", costCp: 200, weight: 6 });
export const mirrorSteel = defineGear({ id: "item:mirror-steel", source, category: "gear", costCp: 500, weight: 0.5 });
export const oilFlask = defineGear({ id: "item:oil-flask", source, category: "gear", costCp: 10, weight: 1 });
export const paperOneSheet = defineGear({ id: "item:paper-one-sheet", source, category: "gear", costCp: 20, weight: 0 });
export const parchmentOneSheet = defineGear({ id: "item:parchment-one-sheet", source, category: "gear", costCp: 10, weight: 0 });
export const perfumeVial = defineGear({ id: "item:perfume-vial", source, category: "gear", costCp: 500, weight: 0 });
export const pickMiners = defineGear({ id: "item:pick-miners", source, category: "gear", costCp: 200, weight: 10 });
export const piton = defineGear({ id: "item:piton", source, category: "gear", costCp: 5, weight: 0.25 });
export const poisonBasicVial = defineGear({ id: "item:poison-basic-vial", source, category: "gear", costCp: 10000, weight: 0 });
export const pole10Foot = defineGear({ id: "item:pole-10-foot", source, category: "gear", costCp: 5, weight: 7 });
export const potIron = defineGear({ id: "item:pot-iron", source, category: "gear", costCp: 200, weight: 10 });
export const pouch = defineGear({ id: "item:pouch", source, category: "gear", costCp: 50, weight: 1 });
export const quiver = defineGear({ id: "item:quiver", source, category: "gear", costCp: 100, weight: 1 });
export const ramPortable = defineGear({ id: "item:ram-portable", source, category: "gear", costCp: 400, weight: 35 });
export const rations1Day = defineGear({ id: "item:rations-1-day", source, category: "gear", costCp: 50, weight: 2 });
export const reliquary = defineGear({ id: "item:reliquary", source, category: "gear", costCp: 500, weight: 2 });
export const robes = defineGear({ id: "item:robes", source, category: "gear", costCp: 100, weight: 4 });
export const ropeHempen50Feet = defineGear({ id: "item:rope-hempen-50-feet", source, category: "gear", costCp: 100, weight: 10 });
export const ropeSilk50Feet = defineGear({ id: "item:rope-silk-50-feet", source, category: "gear", costCp: 1000, weight: 5 });
export const sack = defineGear({ id: "item:sack", source, category: "gear", costCp: 1, weight: 0.5 });
export const scaleMerchants = defineGear({ id: "item:scale-merchants", source, category: "gear", costCp: 500, weight: 3 });
export const sealingWax = defineGear({ id: "item:sealing-wax", source, category: "gear", costCp: 50, weight: 0 });
export const shovel = defineGear({ id: "item:shovel", source, category: "gear", costCp: 200, weight: 5 });
export const signalWhistle = defineGear({ id: "item:signal-whistle", source, category: "gear", costCp: 5, weight: 0 });
export const signetRing = defineGear({ id: "item:signet-ring", source, category: "gear", costCp: 500, weight: 0 });
export const smallKnife = defineGear({ id: "item:small-knife", source, category: "gear", costCp: 0, weight: 0 });
export const soap = defineGear({ id: "item:soap", source, category: "gear", costCp: 2, weight: 0 });
export const spellbook = defineGear({ id: "item:spellbook", source, category: "gear", costCp: 5000, weight: 3 });
export const spikeIron = defineGear({ id: "item:spike-iron", source, category: "gear", costCp: 10, weight: 5 });
export const spyglass = defineGear({ id: "item:spyglass", source, category: "gear", costCp: 100000, weight: 1 });
export const string10Feet = defineGear({ id: "item:string-10-feet", source, category: "gear", costCp: 0, weight: 0 });
export const tentTwoPerson = defineGear({ id: "item:tent-two-person", source, category: "gear", costCp: 200, weight: 20 });
export const tinderbox = defineGear({ id: "item:tinderbox", source, category: "gear", costCp: 50, weight: 1 });
export const torch = defineGear({ id: "item:torch", source, category: "gear", costCp: 1, weight: 1 });
export const vestments = defineGear({ id: "item:vestments", source, category: "gear", costCp: 0, weight: 0 });
export const vial = defineGear({ id: "item:vial", source, category: "gear", costCp: 100, weight: 0 });
export const waterskin = defineGear({ id: "item:waterskin", source, category: "gear", costCp: 20, weight: 5 });
export const whetstone = defineGear({ id: "item:whetstone", source, category: "gear", costCp: 1, weight: 1 });
export const burglarsPack = defineGear({ id: "item:burglars-pack", source, category: "gear", costCp: 1600, weight: null });
export const diplomatsPack = defineGear({ id: "item:diplomats-pack", source, category: "gear", costCp: 3900, weight: null });
export const dungeoneersPack = defineGear({ id: "item:dungeoneers-pack", source, category: "gear", costCp: 1200, weight: null });
export const entertainersPack = defineGear({ id: "item:entertainers-pack", source, category: "gear", costCp: 4000, weight: null });
export const explorersPack = defineGear({ id: "item:explorers-pack", source, category: "gear", costCp: 1000, weight: null });
export const priestsPack = defineGear({ id: "item:priests-pack", source, category: "gear", costCp: 1900, weight: null });
export const scholarsPack = defineGear({ id: "item:scholars-pack", source, category: "gear", costCp: 4000, weight: null });
export const alchemistsSupplies = defineGear({ id: "item:alchemists-supplies", source, category: "tool", costCp: 5000, weight: 8 });
export const brewersSupplies = defineGear({ id: "item:brewers-supplies", source, category: "tool", costCp: 2000, weight: 9 });
export const calligraphersSupplies = defineGear({ id: "item:calligraphers-supplies", source, category: "tool", costCp: 1000, weight: 5 });
export const carpentersTools = defineGear({ id: "item:carpenters-tools", source, category: "tool", costCp: 800, weight: 6 });
export const cartographersTools = defineGear({ id: "item:cartographers-tools", source, category: "tool", costCp: 1500, weight: 6 });
export const cobblersTools = defineGear({ id: "item:cobblers-tools", source, category: "tool", costCp: 500, weight: 5 });
export const cooksUtensils = defineGear({ id: "item:cooks-utensils", source, category: "tool", costCp: 100, weight: 8 });
export const glassblowersTools = defineGear({ id: "item:glassblowers-tools", source, category: "tool", costCp: 3000, weight: 5 });
export const jewelersTools = defineGear({ id: "item:jewelers-tools", source, category: "tool", costCp: 2500, weight: 2 });
export const leatherworkersTools = defineGear({ id: "item:leatherworkers-tools", source, category: "tool", costCp: 500, weight: 5 });
export const masonsTools = defineGear({ id: "item:masons-tools", source, category: "tool", costCp: 1000, weight: 8 });
export const paintersSupplies = defineGear({ id: "item:painters-supplies", source, category: "tool", costCp: 1000, weight: 5 });
export const pottersTools = defineGear({ id: "item:potters-tools", source, category: "tool", costCp: 1000, weight: 3 });
export const smithsTools = defineGear({ id: "item:smiths-tools", source, category: "tool", costCp: 2000, weight: 8 });
export const tinkersTools = defineGear({ id: "item:tinkers-tools", source, category: "tool", costCp: 5000, weight: 10 });
export const weaversTools = defineGear({ id: "item:weavers-tools", source, category: "tool", costCp: 100, weight: 5 });
export const woodcarversTools = defineGear({ id: "item:woodcarvers-tools", source, category: "tool", costCp: 100, weight: 5 });
export const diceSet = defineGear({ id: "item:dice-set", source, category: "tool", costCp: 10, weight: 0 });
export const playingCardSet = defineGear({ id: "item:playing-card-set", source, category: "tool", costCp: 50, weight: 0 });
export const bagpipes = defineGear({ id: "item:bagpipes", source, category: "tool", costCp: 3000, weight: 6 });
export const drum = defineGear({ id: "item:drum", source, category: "tool", costCp: 600, weight: 3 });
export const dulcimer = defineGear({ id: "item:dulcimer", source, category: "tool", costCp: 2500, weight: 10 });
export const flute = defineGear({ id: "item:flute", source, category: "tool", costCp: 200, weight: 1 });
export const lute = defineGear({ id: "item:lute", source, category: "tool", costCp: 3500, weight: 2 });
export const lyre = defineGear({ id: "item:lyre", source, category: "tool", costCp: 3000, weight: 2 });
export const hornInstrument = defineGear({ id: "item:horn-instrument", source, category: "tool", costCp: 300, weight: 2 });
export const panFlute = defineGear({ id: "item:pan-flute", source, category: "tool", costCp: 1200, weight: 2 });
export const shawm = defineGear({ id: "item:shawm", source, category: "tool", costCp: 200, weight: 1 });
export const viol = defineGear({ id: "item:viol", source, category: "tool", costCp: 3000, weight: 1 });
export const navigatorsTools = defineGear({ id: "item:navigators-tools", source, category: "tool", costCp: 2500, weight: 2 });
export const thievesTools = defineGear({ id: "item:thieves-tools", source, category: "tool", costCp: 2500, weight: 1 });
export const camel = defineGear({ id: "item:camel", source, category: "transport", costCp: 5000, weight: null });
export const donkey = defineGear({ id: "item:donkey", source, category: "transport", costCp: 800, weight: null });
export const mule = defineGear({ id: "item:mule", source, category: "transport", costCp: 800, weight: null });
export const elephant = defineGear({ id: "item:elephant", source, category: "transport", costCp: 20000, weight: null });
export const horseDraft = defineGear({ id: "item:horse-draft", source, category: "transport", costCp: 5000, weight: null });
export const horseRiding = defineGear({ id: "item:horse-riding", source, category: "transport", costCp: 7500, weight: null });
export const mastiff = defineGear({ id: "item:mastiff", source, category: "transport", costCp: 2500, weight: null });
export const pony = defineGear({ id: "item:pony", source, category: "transport", costCp: 3000, weight: null });
export const warhorse = defineGear({ id: "item:warhorse", source, category: "transport", costCp: 40000, weight: null });
export const bardingPadded = defineGear({ id: "item:barding-padded", source, category: "transport", costCp: 2000, weight: 16 });
export const bardingLeather = defineGear({ id: "item:barding-leather", source, category: "transport", costCp: 4000, weight: 20 });
export const bardingStuddedLeather = defineGear({ id: "item:barding-studded-leather", source, category: "transport", costCp: 18000, weight: 26 });
export const bardingHide = defineGear({ id: "item:barding-hide", source, category: "transport", costCp: 4000, weight: 24 });
export const bardingChainShirt = defineGear({ id: "item:barding-chain-shirt", source, category: "transport", costCp: 20000, weight: 40 });
export const bardingScaleMail = defineGear({ id: "item:barding-scale-mail", source, category: "transport", costCp: 20000, weight: 90 });
export const bardingBreastplate = defineGear({ id: "item:barding-breastplate", source, category: "transport", costCp: 160000, weight: 40 });
export const bardingHalfPlate = defineGear({ id: "item:barding-half-plate", source, category: "transport", costCp: 300000, weight: 80 });
export const bardingRingMail = defineGear({ id: "item:barding-ring-mail", source, category: "transport", costCp: 1200, weight: 80 });
export const bardingChainMail = defineGear({ id: "item:barding-chain-mail", source, category: "transport", costCp: 30000, weight: 110 });
export const bardingSplint = defineGear({ id: "item:barding-splint", source, category: "transport", costCp: 80000, weight: 120 });
export const bardingPlate = defineGear({ id: "item:barding-plate", source, category: "transport", costCp: 600000, weight: 130 });
export const bitAndBridle = defineGear({ id: "item:bit-and-bridle", source, category: "transport", costCp: 200, weight: 1 });
export const carriage = defineGear({ id: "item:carriage", source, category: "transport", costCp: 10000, weight: 600 });
export const cart = defineGear({ id: "item:cart", source, category: "transport", costCp: 1500, weight: 200 });
export const chariot = defineGear({ id: "item:chariot", source, category: "transport", costCp: 25000, weight: 100 });
export const animalFeed1Day = defineGear({ id: "item:animal-feed-1-day", source, category: "transport", costCp: 5, weight: 10 });
export const saddleExotic = defineGear({ id: "item:saddle-exotic", source, category: "transport", costCp: 6000, weight: 50 });
export const saddleMilitary = defineGear({ id: "item:saddle-military", source, category: "transport", costCp: 2000, weight: 30 });
export const saddlePack = defineGear({ id: "item:saddle-pack", source, category: "transport", costCp: 500, weight: 15 });
export const saddleRiding = defineGear({ id: "item:saddle-riding", source, category: "transport", costCp: 1000, weight: 25 });
export const saddlebags = defineGear({ id: "item:saddlebags", source, category: "transport", costCp: 400, weight: 8 });
export const sled = defineGear({ id: "item:sled", source, category: "transport", costCp: 2000, weight: 300 });
export const stabling1Day = defineGear({ id: "item:stabling-1-day", source, category: "transport", costCp: 50, weight: 0 });
export const wagon = defineGear({ id: "item:wagon", source, category: "transport", costCp: 3500, weight: 400 });
export const galley = defineGear({ id: "item:galley", source, category: "transport", costCp: 3000000, weight: null });
export const keelboat = defineGear({ id: "item:keelboat", source, category: "transport", costCp: 300000, weight: null });
export const longship = defineGear({ id: "item:longship", source, category: "transport", costCp: 1000000, weight: null });
export const rowboat = defineGear({ id: "item:rowboat", source, category: "transport", costCp: 5000, weight: null });
export const sailingShip = defineGear({ id: "item:sailing-ship", source, category: "transport", costCp: 1000000, weight: null });
export const warship = defineGear({ id: "item:warship", source, category: "transport", costCp: 2500000, weight: null });

// What generated monsters bite, claw and slam with. The damage die here is a
// placeholder: each monster's attack carries its own damage.
export const tentacle = defineWeapon({ id: "item:tentacle", source, damage: dice(1, 6), damageType: "bludgeoning", range: melee, finesse: false, natural: true });
export const tail = defineWeapon({ id: "item:tail", source, damage: dice(1, 6), damageType: "bludgeoning", range: melee, finesse: false, natural: true });
export const frightfulPresence = defineWeapon({ id: "item:frightful-presence", source, damage: dice(1, 6), damageType: "psychic", range: melee, finesse: false, natural: true });
export const acidBreath = defineWeapon({ id: "item:acid-breath", source, damage: dice(1, 6), damageType: "acid", range: melee, finesse: false, natural: true });
export const wingAttack = defineWeapon({ id: "item:wing-attack", source, damage: dice(1, 6), damageType: "bludgeoning", range: melee, finesse: false, natural: true });
export const lightningBreath = defineWeapon({ id: "item:lightning-breath", source, damage: dice(1, 6), damageType: "lightning", range: melee, finesse: false, natural: true });
export const poisonBreath = defineWeapon({ id: "item:poison-breath", source, damage: dice(1, 6), damageType: "poison", range: melee, finesse: false, natural: true });
export const fireBreath = defineWeapon({ id: "item:fire-breath", source, damage: dice(1, 6), damageType: "fire", range: melee, finesse: false, natural: true });
export const coldBreath = defineWeapon({ id: "item:cold-breath", source, damage: dice(1, 6), damageType: "cold", range: melee, finesse: false, natural: true });
export const biteSlashing = defineWeapon({ id: "item:bite-slashing", source, damage: dice(1, 6), damageType: "slashing", range: melee, finesse: false, natural: true });
export const acidSpray = defineWeapon({ id: "item:acid-spray", source, damage: dice(1, 6), damageType: "acid", range: melee, finesse: false, natural: true });
export const fist = defineWeapon({ id: "item:fist", source, damage: dice(1, 6), damageType: "bludgeoning", range: melee, finesse: false, natural: true });
export const rock = defineWeapon({ id: "item:rock", source, damage: dice(1, 6), damageType: "bludgeoning", range: { kind: "ranged", normal: 25, long: 50 }, finesse: false, natural: true });
export const rake = defineWeapon({ id: "item:rake", source, damage: dice(1, 6), damageType: "slashing", range: melee, finesse: false, natural: true });
export const beak = defineWeapon({ id: "item:beak", source, damage: dice(1, 6), damageType: "slashing", range: melee, finesse: false, natural: true });
export const clawPiercing = defineWeapon({ id: "item:claw-piercing", source, damage: dice(1, 6), damageType: "piercing", range: melee, finesse: false, natural: true });
export const tailPiercing = defineWeapon({ id: "item:tail-piercing", source, damage: dice(1, 6), damageType: "piercing", range: melee, finesse: false, natural: true });
export const hurlFlame = defineWeapon({ id: "item:hurl-flame", source, damage: dice(1, 6), damageType: "fire", range: melee, finesse: false, natural: true });
export const beard = defineWeapon({ id: "item:beard", source, damage: dice(1, 6), damageType: "piercing", range: melee, finesse: false, natural: true });
export const constrict = defineWeapon({ id: "item:constrict", source, damage: dice(1, 6), damageType: "bludgeoning", range: melee, finesse: false, natural: true });
export const pseudopod = defineWeapon({ id: "item:pseudopod", source, damage: dice(1, 6), damageType: "bludgeoning", range: melee, finesse: false, natural: true });
export const beakPiercing = defineWeapon({ id: "item:beak-piercing", source, damage: dice(1, 6), damageType: "piercing", range: melee, finesse: false, natural: true });
export const sting = defineWeapon({ id: "item:sting", source, damage: dice(1, 6), damageType: "piercing", range: melee, finesse: false, natural: true });
export const biteBludgeoning = defineWeapon({ id: "item:bite-bludgeoning", source, damage: dice(1, 6), damageType: "bludgeoning", range: melee, finesse: false, natural: true });
export const claws = defineWeapon({ id: "item:claws", source, damage: dice(1, 6), damageType: "slashing", range: melee, finesse: false, natural: true });
export const hooves = defineWeapon({ id: "item:hooves", source, damage: dice(1, 6), damageType: "bludgeoning", range: melee, finesse: false, natural: true });
export const chain = defineWeapon({ id: "item:chain", source, damage: dice(1, 6), damageType: "slashing", range: melee, finesse: false, natural: true });
export const horns = defineWeapon({ id: "item:horns", source, damage: dice(1, 6), damageType: "bludgeoning", range: melee, finesse: false, natural: true });
export const pincer = defineWeapon({ id: "item:pincer", source, damage: dice(1, 6), damageType: "bludgeoning", range: melee, finesse: false, natural: true });
export const tailSlashing = defineWeapon({ id: "item:tail-slashing", source, damage: dice(1, 6), damageType: "slashing", range: melee, finesse: false, natural: true });
export const moan = defineWeapon({ id: "item:moan", source, damage: dice(1, 6), damageType: "psychic", range: melee, finesse: false, natural: true });
export const clawBludgeoning = defineWeapon({ id: "item:claw-bludgeoning", source, damage: dice(1, 6), damageType: "bludgeoning", range: melee, finesse: false, natural: true });
export const crush = defineWeapon({ id: "item:crush", source, damage: dice(1, 6), damageType: "bludgeoning", range: melee, finesse: false, natural: true });
export const poisonedDart = defineWeapon({ id: "item:poisoned-dart", source, damage: dice(1, 6), damageType: "piercing", range: { kind: "ranged", normal: 30, long: 120 }, finesse: false, natural: true });
export const steamBreath = defineWeapon({ id: "item:steam-breath", source, damage: dice(1, 6), damageType: "fire", range: melee, finesse: false, natural: true });
export const blindingBreath = defineWeapon({ id: "item:blinding-breath", source, damage: dice(1, 6), damageType: "psychic", range: melee, finesse: false, natural: true });
export const deathBurst = defineWeapon({ id: "item:death-burst", source, damage: dice(1, 6), damageType: "psychic", range: melee, finesse: false, natural: true });
export const talons = defineWeapon({ id: "item:talons", source, damage: dice(1, 6), damageType: "slashing", range: melee, finesse: false, natural: true });
export const gore = defineWeapon({ id: "item:gore", source, damage: dice(1, 6), damageType: "piercing", range: melee, finesse: false, natural: true });
export const stomp = defineWeapon({ id: "item:stomp", source, damage: dice(1, 6), damageType: "bludgeoning", range: melee, finesse: false, natural: true });
export const ram = defineWeapon({ id: "item:ram", source, damage: dice(1, 6), damageType: "bludgeoning", range: melee, finesse: false, natural: true });
export const touch = defineWeapon({ id: "item:touch", source, damage: dice(1, 6), damageType: "fire", range: melee, finesse: false, natural: true });
export const pseudopodAcid = defineWeapon({ id: "item:pseudopod-acid", source, damage: dice(1, 6), damageType: "acid", range: melee, finesse: false, natural: true });
export const witheringTouch = defineWeapon({ id: "item:withering-touch", source, damage: dice(1, 6), damageType: "necrotic", range: melee, finesse: false, natural: true });
export const tentacles = defineWeapon({ id: "item:tentacles", source, damage: dice(1, 6), damageType: "bludgeoning", range: melee, finesse: false, natural: true });
export const bites = defineWeapon({ id: "item:bites", source, damage: dice(1, 6), damageType: "piercing", range: melee, finesse: false, natural: true });
export const blindingSpittle = defineWeapon({ id: "item:blinding-spittle", source, damage: dice(1, 6), damageType: "psychic", range: melee, finesse: false, natural: true });
export const shieldBash = defineWeapon({ id: "item:shield-bash", source, damage: dice(1, 6), damageType: "bludgeoning", range: melee, finesse: false, natural: true });
export const petrifyingBreath = defineWeapon({ id: "item:petrifying-breath", source, damage: dice(1, 6), damageType: "psychic", range: melee, finesse: false, natural: true });
export const tentaclesSlashing = defineWeapon({ id: "item:tentacles-slashing", source, damage: dice(1, 6), damageType: "slashing", range: melee, finesse: false, natural: true });
export const spikedBoneClub = defineWeapon({ id: "item:spiked-bone-club", source, damage: dice(1, 6), damageType: "bludgeoning", range: melee, finesse: false, natural: true });
export const fork = defineWeapon({ id: "item:fork", source, damage: dice(1, 6), damageType: "piercing", range: melee, finesse: false, natural: true });
export const frostBreath = defineWeapon({ id: "item:frost-breath", source, damage: dice(1, 6), damageType: "cold", range: melee, finesse: false, natural: true });
export const deathBurstSlashing = defineWeapon({ id: "item:death-burst-slashing", source, damage: dice(1, 6), damageType: "slashing", range: melee, finesse: false, natural: true });
export const sword = defineWeapon({ id: "item:sword", source, damage: dice(1, 6), damageType: "slashing", range: melee, finesse: false, natural: true });
export const paralyzingTouch = defineWeapon({ id: "item:paralyzing-touch", source, damage: dice(1, 6), damageType: "cold", range: melee, finesse: false, natural: true });
export const deathBurstFire = defineWeapon({ id: "item:death-burst-fire", source, damage: dice(1, 6), damageType: "fire", range: melee, finesse: false, natural: true });
export const tailSpike = defineWeapon({ id: "item:tail-spike", source, damage: dice(1, 6), damageType: "piercing", range: { kind: "ranged", normal: 100, long: 200 }, finesse: false, natural: true });
export const snakeHair = defineWeapon({ id: "item:snake-hair", source, damage: dice(1, 6), damageType: "piercing", range: melee, finesse: false, natural: true });
export const harpoon = defineWeapon({ id: "item:harpoon", source, damage: dice(1, 6), damageType: "piercing", range: { kind: "ranged", normal: 20, long: 60 }, finesse: false, natural: true });
export const rottingFist = defineWeapon({ id: "item:rotting-fist", source, damage: dice(1, 6), damageType: "bludgeoning", range: melee, finesse: false, natural: true });
export const horrorNimbus = defineWeapon({ id: "item:horror-nimbus", source, damage: dice(1, 6), damageType: "psychic", range: melee, finesse: false, natural: true });
export const tailStinger = defineWeapon({ id: "item:tail-stinger", source, damage: dice(1, 6), damageType: "piercing", range: melee, finesse: false, natural: true });
export const goreBludgeoning = defineWeapon({ id: "item:gore-bludgeoning", source, damage: dice(1, 6), damageType: "bludgeoning", range: melee, finesse: false, natural: true });
export const strengthDrain = defineWeapon({ id: "item:strength-drain", source, damage: dice(1, 6), damageType: "necrotic", range: melee, finesse: false, natural: true });
export const slayingLongbow = defineWeapon({ id: "item:slaying-longbow", source, damage: dice(1, 6), damageType: "piercing", range: { kind: "ranged", normal: 150, long: 600 }, finesse: false, natural: true });
export const bloodDrain = defineWeapon({ id: "item:blood-drain", source, damage: dice(1, 6), damageType: "piercing", range: melee, finesse: false, natural: true });
export const beaks = defineWeapon({ id: "item:beaks", source, damage: dice(1, 6), damageType: "piercing", range: melee, finesse: false, natural: true });
export const hornsPiercing = defineWeapon({ id: "item:horns-piercing", source, damage: dice(1, 6), damageType: "piercing", range: melee, finesse: false, natural: true });
export const horn = defineWeapon({ id: "item:horn", source, damage: dice(1, 6), damageType: "piercing", range: melee, finesse: false, natural: true });
export const unarmedStrike = defineWeapon({ id: "item:unarmed-strike", source, damage: dice(1, 6), damageType: "bludgeoning", range: melee, finesse: false, natural: true });
export const rottingTouch = defineWeapon({ id: "item:rotting-touch", source, damage: dice(1, 6), damageType: "necrotic", range: melee, finesse: false, natural: true });
export const stunningScreech = defineWeapon({ id: "item:stunning-screech", source, damage: dice(1, 6), damageType: "psychic", range: melee, finesse: false, natural: true });
export const tusks = defineWeapon({ id: "item:tusks", source, damage: dice(1, 6), damageType: "slashing", range: melee, finesse: false, natural: true });
export const shock = defineWeapon({ id: "item:shock", source, damage: dice(1, 6), damageType: "lightning", range: melee, finesse: false, natural: true });
export const stinger = defineWeapon({ id: "item:stinger", source, damage: dice(1, 6), damageType: "piercing", range: melee, finesse: false, natural: true });

export const srd51GeneratedItems: readonly ItemDefinition[] = [
  handaxe,
  lightHammer,
  sickle,
  dart,
  sling,
  battleaxe,
  flail,
  glaive,
  greatsword,
  halberd,
  lance,
  maul,
  pike,
  trident,
  warPick,
  warhammer,
  whip,
  blowgun,
  handCrossbow,
  heavyCrossbow,
  paddedArmor,
  studdedLeatherArmor,
  chainShirt,
  scaleMail,
  breastplate,
  halfPlateArmor,
  ringMail,
  splintArmor,
  plateArmor,
  abacus,
  acidVial,
  alchemistsFireFlask,
  almsBox,
  arrow,
  blockOfIncense,
  blowgunNeedle,
  censer,
  crossbowBolt,
  slingBullet,
  amulet,
  antitoxinVial,
  crystal,
  orb,
  rod,
  staff,
  wand,
  backpack,
  ballBearingsBagOf1000,
  barrel,
  basket,
  bedroll,
  bell,
  blanket,
  blockAndTackle,
  book,
  bottleGlass,
  bucket,
  caltrops,
  candle,
  caseCrossbowBolt,
  caseMapOrScroll,
  chain10Feet,
  chalk1Piece,
  chest,
  clothesCommon,
  clothesCostume,
  clothesFine,
  clothesTravelers,
  componentPouch,
  crowbar,
  sprigOfMistletoe,
  totem,
  woodenStaff,
  yewWand,
  emblem,
  fishingTackle,
  flaskOrTankard,
  grapplingHook,
  hammer,
  hammerSledge,
  holyWaterFlask,
  hourglass,
  huntingTrap,
  ink1OunceBottle,
  inkPen,
  jugOrPitcher,
  climbersKit,
  disguiseKit,
  forgeryKit,
  herbalismKit,
  healersKit,
  messKit,
  poisonersKit,
  ladder10Foot,
  lamp,
  lanternBullseye,
  lanternHooded,
  littleBagOfSand,
  lock,
  magnifyingGlass,
  manacles,
  mirrorSteel,
  oilFlask,
  paperOneSheet,
  parchmentOneSheet,
  perfumeVial,
  pickMiners,
  piton,
  poisonBasicVial,
  pole10Foot,
  potIron,
  pouch,
  quiver,
  ramPortable,
  rations1Day,
  reliquary,
  robes,
  ropeHempen50Feet,
  ropeSilk50Feet,
  sack,
  scaleMerchants,
  sealingWax,
  shovel,
  signalWhistle,
  signetRing,
  smallKnife,
  soap,
  spellbook,
  spikeIron,
  spyglass,
  string10Feet,
  tentTwoPerson,
  tinderbox,
  torch,
  vestments,
  vial,
  waterskin,
  whetstone,
  burglarsPack,
  diplomatsPack,
  dungeoneersPack,
  entertainersPack,
  explorersPack,
  priestsPack,
  scholarsPack,
  alchemistsSupplies,
  brewersSupplies,
  calligraphersSupplies,
  carpentersTools,
  cartographersTools,
  cobblersTools,
  cooksUtensils,
  glassblowersTools,
  jewelersTools,
  leatherworkersTools,
  masonsTools,
  paintersSupplies,
  pottersTools,
  smithsTools,
  tinkersTools,
  weaversTools,
  woodcarversTools,
  diceSet,
  playingCardSet,
  bagpipes,
  drum,
  dulcimer,
  flute,
  lute,
  lyre,
  hornInstrument,
  panFlute,
  shawm,
  viol,
  navigatorsTools,
  thievesTools,
  camel,
  donkey,
  mule,
  elephant,
  horseDraft,
  horseRiding,
  mastiff,
  pony,
  warhorse,
  bardingPadded,
  bardingLeather,
  bardingStuddedLeather,
  bardingHide,
  bardingChainShirt,
  bardingScaleMail,
  bardingBreastplate,
  bardingHalfPlate,
  bardingRingMail,
  bardingChainMail,
  bardingSplint,
  bardingPlate,
  bitAndBridle,
  carriage,
  cart,
  chariot,
  animalFeed1Day,
  saddleExotic,
  saddleMilitary,
  saddlePack,
  saddleRiding,
  saddlebags,
  sled,
  stabling1Day,
  wagon,
  galley,
  keelboat,
  longship,
  rowboat,
  sailingShip,
  warship,
  tentacle,
  tail,
  frightfulPresence,
  acidBreath,
  wingAttack,
  lightningBreath,
  poisonBreath,
  fireBreath,
  coldBreath,
  biteSlashing,
  acidSpray,
  fist,
  rock,
  rake,
  beak,
  clawPiercing,
  tailPiercing,
  hurlFlame,
  beard,
  constrict,
  pseudopod,
  beakPiercing,
  sting,
  biteBludgeoning,
  claws,
  hooves,
  chain,
  horns,
  pincer,
  tailSlashing,
  moan,
  clawBludgeoning,
  crush,
  poisonedDart,
  steamBreath,
  blindingBreath,
  deathBurst,
  talons,
  gore,
  stomp,
  ram,
  touch,
  pseudopodAcid,
  witheringTouch,
  tentacles,
  bites,
  blindingSpittle,
  shieldBash,
  petrifyingBreath,
  tentaclesSlashing,
  spikedBoneClub,
  fork,
  frostBreath,
  deathBurstSlashing,
  sword,
  paralyzingTouch,
  deathBurstFire,
  tailSpike,
  snakeHair,
  harpoon,
  rottingFist,
  horrorNimbus,
  tailStinger,
  goreBludgeoning,
  strengthDrain,
  slayingLongbow,
  bloodDrain,
  beaks,
  hornsPiercing,
  horn,
  unarmedStrike,
  rottingTouch,
  stunningScreech,
  tusks,
  shock,
  stinger,
];
