import { readFileSync, writeFileSync } from "node:fs";

// The conversion guide, the format reference and the template are written once, in docs/, for people and for any outside model. The bot's own
// Adventure Author reads the same words; the runtime image has no docs/ folder, so they are copied into a module here (and a test fails when
// the copy is stale):  npm run adventure:guide
const read = (path: string): string => readFileSync(new URL(`../../docs/${path}`, import.meta.url), "utf8").replaceAll("\r\n", "\n");

export function authoringGuideModule(): string {
  const parts = {
    conversionGuide: read("dnd-adventure-conversion-guide.md"),
    formatReference: read("dnd-adventure-authoring.md"),
    template: read("adventure-template.yaml"),
  };
  return [
    "// Generated by `npm run adventure:guide` from docs/. Do not edit: change the docs and run it again.",
    ...Object.entries(parts).map(([name, text]) => `export const ${name}: string = ${JSON.stringify(text)};`),
    "",
  ].join("\n");
}

if (process.argv[1]?.endsWith("build-authoring-guide.ts")) {
  writeFileSync(new URL("../application/campaign/adventures/authoring-guide.generated.ts", import.meta.url), authoringGuideModule());
  console.log("authoring-guide.generated.ts written");
}
