import { defineFeature, type FeatureDefinition } from "../../../rules/content-definitions.js";

// Class features from level 6 up, and the subclass features that come with them (SRD 5.1, Classes).
// Most are named on the sheet only: they act outside a fight, or need a rule the engine does not have
// (docs/dnd-completion-roadmap.md). Those with a trait are read where that rule applies.
const source = "SRD 5.1";

const narrative = (name: string): FeatureDefinition => defineFeature({ id: `feature:${name}`, source, traits: [], action: null });

export const mindlessRage = narrative("mindless-rage");
export const intimidatingPresence = narrative("intimidating-presence");
export const retaliation = narrative("retaliation");
export const persistentRage = narrative("persistent-rage");
export const indomitableMight = defineFeature({ id: "feature:indomitable-might", source, traits: [{ kind: "indomitableMight" }], action: null });
export const primalChampion = narrative("primal-champion");
export const songOfRest = narrative("song-of-rest");
export const cuttingWords = narrative("cutting-words");
export const countercharm = narrative("countercharm");
export const additionalMagicalSecrets = narrative("additional-magical-secrets");
export const magicalSecrets = narrative("magical-secrets");
export const peerlessSkill = narrative("peerless-skill");
export const superiorInspiration = narrative("superior-inspiration");
export const blessedHealer = narrative("blessed-healer");
export const divineStrike = narrative("divine-strike");
export const divineIntervention = narrative("divine-intervention");
export const supremeHealing = narrative("supreme-healing");
export const landsStride = narrative("lands-stride");
export const naturesWard = narrative("natures-ward");
export const naturesSanctuary = narrative("natures-sanctuary");
export const timelessBody = narrative("timeless-body");
export const beastSpells = narrative("beast-spells");
export const archdruid = narrative("archdruid");
export const additionalFightingStyle = narrative("additional-fighting-style");
export const survivor = defineFeature({ id: "feature:survivor", source, traits: [{ kind: "survivor" }], action: null });
export const deflectMissiles = narrative("deflect-missiles");
export const openHandTechnique = narrative("open-hand-technique");
export const slowFall = narrative("slow-fall");
export const kiEmpoweredStrikes = narrative("ki-empowered-strikes");
export const wholenessOfBody = narrative("wholeness-of-body");
export const stillnessOfMind = narrative("stillness-of-mind");
export const tranquility = narrative("tranquility");
export const tongueOfTheSunAndMoon = narrative("tongue-of-the-sun-and-moon");
export const diamondSoul = narrative("diamond-soul");
export const timelessBodyMonk = narrative("timeless-body-monk");
export const quiveringPalm = narrative("quivering-palm");
export const emptyBody = narrative("empty-body");
export const perfectSelf = narrative("perfect-self");
export const divineHealth = narrative("divine-health");
export const auraOfDevotion = narrative("aura-of-devotion");
export const cleansingTouch = narrative("cleansing-touch");
export const purityOfHeart = narrative("purity-of-heart");
export const holyNimbus = narrative("holy-nimbus");
export const primevalAwareness = narrative("primeval-awareness");
export const defensiveTactics = narrative("defensive-tactics");
export const rangersLandsStride = narrative("rangers-lands-stride");
export const hideInPlainSight = narrative("hide-in-plain-sight");
export const hunterMultiattack = narrative("hunter-multiattack");
export const vanish = narrative("vanish");
export const superiorHuntersDefense = narrative("superior-hunters-defense");
export const feralSenses = narrative("feral-senses");
export const foeSlayer = narrative("foe-slayer");
export const fastHands = narrative("fast-hands");
export const secondStoryWork = narrative("second-story-work");
export const supremeSneak = narrative("supreme-sneak");
export const useMagicDevice = narrative("use-magic-device");
export const blindsense = narrative("blindsense");
export const slipperyMind = narrative("slippery-mind");
export const thiefsReflexes = narrative("thiefs-reflexes");
export const elusive = defineFeature({ id: "feature:elusive", source, traits: [{ kind: "elusive" }], action: null });
export const strokeOfLuck = narrative("stroke-of-luck");
export const elementalAffinity = narrative("elemental-affinity");
export const metamagicAdditional = narrative("metamagic-additional");
export const dragonWings = narrative("dragon-wings");
export const draconicPresence = narrative("draconic-presence");
export const sorcerousRestoration = narrative("sorcerous-restoration");
export const darkOnesBlessing = narrative("dark-ones-blessing");
export const darkOnesOwnLuck = narrative("dark-ones-own-luck");
export const fiendishResilience = narrative("fiendish-resilience");
export const mysticArcanum6 = narrative("mystic-arcanum-6");
export const mysticArcanum7 = narrative("mystic-arcanum-7");
export const hurlThroughHell = narrative("hurl-through-hell");
export const mysticArcanum8 = narrative("mystic-arcanum-8");
export const mysticArcanum9 = narrative("mystic-arcanum-9");
export const eldritchMaster = narrative("eldritch-master");
export const sculptSpells = narrative("sculpt-spells");
export const potentCantrip = narrative("potent-cantrip");
export const empoweredEvocation = narrative("empowered-evocation");
export const overchannel = narrative("overchannel");
export const spellMastery = narrative("spell-mastery");
export const signatureSpells = narrative("signature-spells");

export const srd51LateFeatures: readonly FeatureDefinition[] = [mindlessRage, intimidatingPresence, retaliation, persistentRage, indomitableMight, primalChampion, songOfRest, cuttingWords, countercharm, additionalMagicalSecrets, magicalSecrets, peerlessSkill, superiorInspiration, blessedHealer, divineStrike, divineIntervention, supremeHealing, landsStride, naturesWard, naturesSanctuary, timelessBody, beastSpells, archdruid, additionalFightingStyle, survivor, deflectMissiles, openHandTechnique, slowFall, kiEmpoweredStrikes, wholenessOfBody, stillnessOfMind, tranquility, tongueOfTheSunAndMoon, diamondSoul, timelessBodyMonk, quiveringPalm, emptyBody, perfectSelf, divineHealth, auraOfDevotion, cleansingTouch, purityOfHeart, holyNimbus, primevalAwareness, defensiveTactics, rangersLandsStride, hideInPlainSight, hunterMultiattack, vanish, superiorHuntersDefense, feralSenses, foeSlayer, fastHands, secondStoryWork, supremeSneak, useMagicDevice, blindsense, slipperyMind, thiefsReflexes, elusive, strokeOfLuck, elementalAffinity, metamagicAdditional, dragonWings, draconicPresence, sorcerousRestoration, darkOnesBlessing, darkOnesOwnLuck, fiendishResilience, mysticArcanum6, mysticArcanum7, hurlThroughHell, mysticArcanum8, mysticArcanum9, eldritchMaster, sculptSpells, potentCantrip, empoweredEvocation, overchannel, spellMastery, signatureSpells];
