// What each class, race and action feature does, in a sentence or two, after SRD 5.1 (2014). The words are the table's reference: the engine decides every outcome.
// Each entry: [feature id without "feature:", English, Chinese].
const entries = [
  // Actions every hero can take
  ["grapple", "Action: a Strength (Athletics) contest against the target's Strength (Athletics) or Dexterity (Acrobatics). On a win the target's speed becomes 0.", "動作：以力量（運動）對抗目標的力量（運動）或敏捷（特技）。成功則目標速度變為 0。"],
  ["escape-grapple", "Action: a Strength (Athletics) or Dexterity (Acrobatics) contest against the grappler to break free.", "動作：以力量（運動）或敏捷（特技）對抗擒抱者，掙脫擒抱。"],
  ["shove", "Action: a Strength (Athletics) contest against the target. On a win you knock it prone or push it 5 feet away.", "動作：以力量（運動）對抗目標。成功則將其推倒，或推開 5 呎。"],
  ["help", "Action: give a creature advantage on its next check for a task, or on its next attack against a foe within 5 feet of you.", "動作：讓一個生物下一次執行該任務的檢定具有優勢，或讓其下一次攻擊你 5 呎內的敵人時具有優勢。"],
  ["hide", "Action: a Dexterity (Stealth) check to slip out of sight. It only works when nothing can see you.", "動作：進行敏捷（隱匿）檢定來躲開視線；只有在沒有任何東西看得見你時才有效。"],
  ["ready", "Action: pick a trigger and an action. When the trigger happens before your next turn, you spend your reaction to take it.", "動作：選定觸發條件與動作；在你下個回合之前觸發時，花費反應來執行。"],
  ["hold-reactions", "Keep your reaction for yourself: it is not spent on its own until you use reactions again.", "保留你的反應：在你重新使用反應之前，不會自動消耗。"],
  ["resume-reactions", "Let your reaction be used again when the moment comes.", "讓你的反應在時機出現時可以再度使用。"],

  // Barbarian
  ["rage", "Bonus action. For a minute you have advantage on Strength checks and saves, deal extra damage with Strength melee attacks, and resist bludgeoning, piercing and slashing damage. It ends early if you neither attack nor take damage. A limited number of uses come back on a long rest.", "附贈動作。持續一分鐘：力量檢定與豁免具有優勢、力量近戰攻擊造成額外傷害，並抵抗鈍擊、穿刺與揮砍傷害。若你既沒攻擊也沒受傷就會提早結束。次數有限，長休後恢復。"],
  ["reckless-attack", "On your first attack of a turn you may attack with advantage using Strength, but attacks against you have advantage until your next turn.", "你回合中的第一次攻擊可以使用力量並具有優勢，但直到你下個回合前，對你的攻擊都具有優勢。"],
  ["danger-sense", "Advantage on Dexterity saves against effects you can see, such as traps and spells, as long as you are not blinded, deafened or incapacitated.", "對你看得見的效果（如陷阱與法術）所做的敏捷豁免具有優勢，前提是你沒有目盲、耳聾或失能。"],
  ["fast-movement", "Your speed is 10 feet higher while you wear no heavy armor.", "只要沒有穿重甲，你的速度增加 10 呎。"],
  ["feral-instinct", "Advantage on initiative rolls. If you are surprised you can still act normally on your first turn by raging.", "先攻擲骰具有優勢。若你遭到突襲，只要在第一個回合進入狂暴就能正常行動。"],
  ["brutal-critical", "When you score a critical hit with a melee attack you roll one extra weapon damage die.", "近戰攻擊造成重擊時，額外擲一顆武器傷害骰。"],
  ["brutal-critical-2", "Your melee critical hits roll two extra weapon damage dice.", "近戰重擊時額外擲兩顆武器傷害骰。"],
  ["brutal-critical-3", "Your melee critical hits roll three extra weapon damage dice.", "近戰重擊時額外擲三顆武器傷害骰。"],
  ["relentless-rage", "If you drop to 0 hit points while raging, make a Constitution save (DC 10, rising by 5 each use). On a success you stay up with 1 hit point instead.", "狂暴中生命降到 0 時，進行體質豁免（難度 10，每次使用後 +5）。成功則以 1 點生命值留在場上。"],
  ["persistent-rage", "Your rage ends early only if you fall unconscious or choose to end it.", "你的狂暴只有在你昏迷或自行結束時才會提早終止。"],
  ["indomitable-might", "If your total on a Strength check is lower than your Strength score, you use the score instead.", "力量檢定的總值若低於你的力量屬性值，就以屬性值取代。"],
  ["primal-champion", "Your Strength and Constitution each rise by 4, to a maximum of 24.", "你的力量與體質各提高 4 點，上限 24。"],
  ["path-of-the-berserker", "Your Primal Path. It brings Frenzy, Mindless Rage, Intimidating Presence and Retaliation.", "你的原初之道，帶來狂怒、無心之怒、威嚇氣勢與反擊。"],
  ["mindless-rage", "You cannot be charmed or frightened while raging, and one already on you is suspended.", "狂暴期間你不會被魅惑或恐慌，已有的效果也會暫停。"],
  ["intimidating-presence", "Action: frighten a creature you can see within 30 feet unless it makes a Wisdom save. You can renew it each turn.", "動作：你 30 呎內看得見的一個生物須通過感知豁免，否則陷入恐慌。你可以每回合延續此效果。"],
  ["retaliation", "Reaction: when a creature within 5 feet damages you, make a melee attack against it.", "反應：5 呎內的生物對你造成傷害時，對其進行一次近戰攻擊。"],

  // Bard
  ["bardic-inspiration", "Bonus action: give a creature within 60 feet an inspiration die to add to one check, attack or save within the next ten minutes. Uses equal your Charisma modifier and come back on a long rest.", "附贈動作：給 60 呎內的一個生物一顆鼓舞骰，十分鐘內可加在一次檢定、攻擊或豁免上。次數等於你的魅力調整值，長休後恢復。"],
  ["song-of-rest", "During a short rest, allies who spend Hit Dice to heal regain an extra die of healing.", "短休時，花費生命骰療傷的盟友額外恢復一顆骰子的生命值。"],
  ["jack-of-all-trades", "You add half your proficiency bonus to any ability check you are not already proficient in.", "你尚未熟練的屬性檢定，可加上一半熟練加值。"],
  ["cutting-words", "Reaction: spend an inspiration use to subtract the die from a creature's attack, damage or ability check within 60 feet.", "反應：消耗一次鼓舞，從 60 呎內生物的攻擊、傷害或屬性檢定中扣掉該骰值。"],
  ["countercharm", "Action: until your next turn, you and friendly creatures within 30 feet have advantage on saves against being frightened or charmed.", "動作：直到你下個回合，你與 30 呎內的友方對抗恐慌與魅惑的豁免具有優勢。"],
  ["font-of-inspiration", "Your Bardic Inspiration uses come back on a short rest as well as a long rest.", "你的吟遊鼓舞次數在短休與長休後都會恢復。"],
  ["magical-secrets", "You learn two spells of your choice from any class. They count as bard spells.", "從任何職業中學會兩個法術，視為吟遊詩人法術。"],
  ["additional-magical-secrets", "You learn two more spells from any class's list.", "再從任何職業的法術表中學會兩個法術。"],
  ["superior-inspiration", "When you roll initiative with no Bardic Inspiration left, you regain one use.", "擲先攻時若已沒有吟遊鼓舞次數，恢復一次。"],
  ["college-of-lore", "Your Bard College. It brings Cutting Words, extra proficiencies and, later, Peerless Skill.", "你的吟遊學院，帶來尖刻言辭、額外熟練項目，之後還有無雙技藝。"],
  ["peerless-skill", "Spend an inspiration use to add the die to one of your own ability checks.", "消耗一次鼓舞，把骰值加到你自己的一次屬性檢定上。"],

  // Cleric
  ["channel-divinity", "Draw on divine power for an effect your faith grants, such as turning undead. It comes back on a short or long rest.", "引導信仰之力產生效果，例如驅逐不死生物。短休或長休後恢復。"],
  ["destroy-undead", "When your Turn Undead affects an undead of low enough challenge rating, it is destroyed instead.", "驅逐不死生物時，挑戰等級夠低的不死生物會被直接消滅。"],
  ["divine-intervention", "Call on your deity for aid. Roll a d100; if it is equal to or lower than your cleric level, the god helps. It then rests for seven days.", "向神祇求助。擲 d100，若結果小於或等於你的牧師等級，神祇便出手相助，之後七天內不能再用。"],
  ["disciple-of-life", "Spells of 1st level or higher that heal restore extra hit points: 2 plus the spell's level.", "1 環以上的治療法術額外恢復 2 點加上法術環級的生命值。"],
  ["blessed-healer", "When you heal another creature with a spell, you also regain hit points: 2 plus the spell's level.", "以法術治療他人時，你自己也恢復 2 點加上法術環級的生命值。"],
  ["divine-strike", "Once per turn, a weapon hit deals extra damage of your domain's type (1d8, 2d8 from 14th level).", "每回合一次，武器命中時造成你神域類型的額外傷害（1d8，14 級起 2d8）。"],
  ["supreme-healing", "When a healing spell would roll dice to heal, you use the highest number each die can show instead.", "治療法術原本要擲骰時，改取每顆骰子的最大值。"],

  // Druid
  ["wild-shape", "Action: take the shape of a beast you have seen. Your hit points become the beast's; when they run out you return to your own form with the damage left over. A couple of uses come back on a short rest.", "動作：變成你見過的野獸。你的生命值改為野獸的；耗盡時恢復原形，多出的傷害由原形承受。次數有限，短休後恢復。"],
  ["druidic", "You know Druidic, the secret language of druids, and can leave hidden messages in it.", "你懂得德魯伊的祕密語言「德魯伊語」，並能用它留下隱藏訊息。"],
  ["circle-of-the-land", "Your Druid Circle. You gain extra spells for your terrain and Natural Recovery: on a short rest, regain some spell slots.", "你的德魯伊結社。依地形獲得額外法術，並有自然恢復：短休時恢復部分法術位。"],
  ["lands-stride", "You move through nonmagical difficult terrain without extra cost and have advantage on saves against plants that impede movement.", "穿過非魔法的困難地形不需額外移動力，對抗會阻礙移動的植物的豁免具有優勢。"],
  ["natures-ward", "You are immune to poison and disease and cannot be charmed or frightened by elementals or fey.", "你免疫毒素與疾病，也不會被元素生物或妖精魅惑或恐慌。"],
  ["natures-sanctuary", "Beasts and plants must make a Wisdom save to attack you; on a failure they must pick another target or lose the attack.", "野獸與植物攻擊你前須通過感知豁免，失敗則必須另選目標，否則失去該次攻擊。"],
  ["beast-spells", "You can cast spells while in Wild Shape, using verbal and somatic parts.", "變形期間仍可施放法術。"],
  ["archdruid", "You use Wild Shape as often as you like and can cast druid spells without verbal or somatic parts.", "你可以不限次數使用野性變形，施放德魯伊法術也不需要言語或姿勢成分。"],
  ["timeless-body", "You age more slowly: ten years of time pass for you as one.", "你的老化變慢：每十年對你只相當於一年。"],
  ["primeval-awareness", "Spend a spell slot to sense whether certain kinds of creatures are within a mile of you.", "消耗一個法術位，感知一英里內是否有特定種類的生物。"],

  // Fighter
  ["second-wind", "Bonus action: regain 1d10 plus your fighter level in hit points. It comes back on a short or long rest.", "附贈動作：恢復 1d10 加上你戰士等級的生命值。短休或長休後恢復。"],
  ["action-surge", "Take one additional action on your turn. It comes back on a short or long rest.", "在你的回合額外執行一個動作。短休或長休後恢復。"],
  ["extra-attack", "When you take the Attack action you attack twice.", "執行攻擊動作時可攻擊兩次。"],
  ["extra-attack-2", "When you take the Attack action you attack three times.", "執行攻擊動作時可攻擊三次。"],
  ["extra-attack-3", "When you take the Attack action you attack four times.", "執行攻擊動作時可攻擊四次。"],
  ["indomitable", "Reroll a saving throw you fail, and keep the new roll. It comes back on a long rest.", "重擲一次失敗的豁免並採用新結果。長休後恢復。"],
  ["fighting-style-archery", "You gain +2 to attack rolls you make with ranged weapons.", "使用遠程武器的攻擊骰 +2。"],
  ["fighting-style-defense", "While you wear armor you gain +1 to Armor Class.", "穿著護甲時，護甲等級 +1。"],
  ["fighting-style-dueling", "While you wield a melee weapon in one hand and nothing in the other, you gain +2 to its damage rolls.", "單手持近戰武器、另一手空著時，該武器傷害 +2。"],
  ["fighting-style-protection", "Reaction: while you hold a shield, impose disadvantage on an attack against a creature next to you.", "反應：持盾時，讓攻擊你身旁生物的一次攻擊具有劣勢。"],
  ["fighting-style-two-weapon-fighting", "You add your ability modifier to the damage of your off-hand attack.", "副手攻擊的傷害可加上屬性調整值。"],
  ["additional-fighting-style", "You learn a second Fighting Style.", "再學會一種戰鬥風格。"],
  ["champion", "Improved Critical: your weapon attacks score a critical hit on a roll of 19 or 20. Remarkable Athlete adds half your proficiency bonus to Strength, Dexterity and Constitution checks you are not proficient in.", "強化重擊：武器攻擊擲出 19 或 20 即為重擊。卓越運動員：力量、敏捷、體質檢定若尚未熟練，可加上一半熟練加值。"],
  ["superior-critical", "Your weapon attacks score a critical hit on a roll of 18, 19 or 20.", "武器攻擊擲出 18、19 或 20 即為重擊。"],
  ["survivor", "At the start of each turn, if you have fewer than half your hit points and at least 1, you regain 5 plus your Constitution modifier.", "每回合開始時，若生命值低於一半且至少有 1 點，恢復 5 點加上體質調整值的生命值。"],

  // Monk
  ["martial-arts", "Unarmed strikes and monk weapons use a martial arts die and your Dexterity, and after an Attack action you can make one unarmed strike as a bonus action.", "徒手攻擊與武僧武器使用武術骰並可用敏捷；執行攻擊動作後，可用附贈動作進行一次徒手攻擊。"],
  ["ki", "A pool of ki points, equal to your monk level, fuels your special techniques. They come back on a short or long rest.", "你有等同武僧等級的氣點，用來施展特殊技巧。短休或長休後恢復。"],
  ["flurry-of-blows", "Spend 1 ki after the Attack action to make two unarmed strikes as a bonus action.", "攻擊動作後花 1 點氣，以附贈動作進行兩次徒手攻擊。"],
  ["patient-defense", "Spend 1 ki to take the Dodge action as a bonus action.", "花 1 點氣，以附贈動作執行閃避。"],
  ["step-of-the-wind", "Spend 1 ki to Disengage or Dash as a bonus action; your jump distance doubles for the turn.", "花 1 點氣，以附贈動作脫離或疾走；本回合跳躍距離加倍。"],
  ["unarmored-movement", "Your speed rises by 10 feet while you wear no armor and carry no shield.", "沒有穿護甲也沒持盾時，速度增加 10 呎。"],
  ["unarmored-movement-6", "Your unarmored speed bonus grows, and you can run along walls and across liquids on your turn.", "徒手移動的速度加成提高，且回合中可沿牆壁與水面奔跑。"],
  ["unarmored-movement-10", "Your unarmored speed bonus grows again.", "徒手移動的速度加成再次提高。"],
  ["unarmored-movement-14", "Your unarmored speed bonus grows again.", "徒手移動的速度加成再次提高。"],
  ["unarmored-movement-18", "Your unarmored speed bonus reaches its peak.", "徒手移動的速度加成達到最高。"],
  ["deflect-missiles", "Reaction: reduce the damage from a ranged weapon attack by 1d10 plus your Dexterity modifier and level. If it drops to 0 you can catch it and throw it back.", "反應：把遠程武器攻擊的傷害減少 1d10 加上敏捷調整值與你的等級。若降為 0，你可以接住並擲回。"],
  ["slow-fall", "Reaction: reduce falling damage by five times your monk level.", "反應：把墜落傷害減少你武僧等級的五倍。"],
  ["stunning-strike", "When you hit with a melee weapon attack, spend 1 ki to force a Constitution save. On a failure the target is stunned until the end of your next turn.", "近戰武器攻擊命中時，花 1 點氣迫使目標進行體質豁免，失敗則震懾至你下個回合結束。"],
  ["ki-empowered-strikes", "Your unarmed strikes count as magical for overcoming resistance and immunity.", "你的徒手攻擊視為魔法，可穿透抗性與免疫。"],
  ["evasion", "On a Dexterity save for half damage, you take none if you succeed and half if you fail.", "對需要敏捷豁免的半傷效果，成功則不受傷、失敗則只受一半傷害。"],
  ["stillness-of-mind", "Action: end one effect on you that is charming or frightening you.", "動作：結束你身上一個魅惑或恐慌的效果。"],
  ["purity-of-body", "You are immune to disease and poison.", "你免疫疾病與毒素。"],
  ["tongue-of-the-sun-and-moon", "You can understand every spoken language, and any creature that understands a language can understand you.", "你聽得懂所有口說語言，任何懂得某種語言的生物也聽得懂你。"],
  ["diamond-soul", "You are proficient in every saving throw, and can spend ki to reroll a failed one.", "你熟練所有豁免，並可花費氣重擲失敗的豁免。"],
  ["timeless-body-monk", "You no longer suffer the frailty of old age, and you need no food or water.", "你不再受老化的衰弱影響，也不需要飲食。"],
  ["empty-body", "Spend 4 ki to turn invisible for a minute and resist all damage but force.", "花 4 點氣，一分鐘內隱形並抵抗力場以外的所有傷害。"],
  ["perfect-self", "When you roll initiative with no ki left, you regain 4 points.", "擲先攻時若氣點用盡，恢復 4 點。"],
  ["way-of-the-open-hand", "Your Monastic Tradition: masters of unarmed combat, with Open Hand Technique, Wholeness of Body and Quivering Palm.", "你的武僧傳承：徒手格鬥大師，擁有開掌技巧、身心完整與震顫掌。"],
  ["open-hand-technique", "When you hit with a Flurry of Blows strike you may knock the target prone, push it 15 feet, or deny its reactions.", "疾風連擊命中時，可選擇讓目標倒地、推開 15 呎，或使其無法使用反應。"],
  ["wholeness-of-body", "Action: heal yourself for three times your monk level. It comes back on a long rest.", "動作：為自己恢復武僧等級三倍的生命值。長休後恢復。"],
  ["quivering-palm", "Spend 3 ki on a hit to start lethal vibrations in the target; later, use your action to end them. The target must save or drop to 0 hit points, or take heavy necrotic damage.", "命中時花 3 點氣，在目標體內種下致命震動；之後用動作引發。目標須豁免，失敗則生命降為 0，成功仍受大量死靈傷害。"],

  // Paladin
  ["divine-sense", "Action: until the end of your next turn, you know where any celestial, fiend or undead within 60 feet is. Uses depend on your Charisma modifier.", "動作：直到你下個回合結束，你知道 60 呎內所有天界生物、邪魔與不死生物的位置。次數取決於魅力調整值。"],
  ["lay-on-hands", "A pool of healing equal to five times your paladin level. Touch a creature to restore hit points from it, or spend 5 points to cure a disease or poison. It refills on a long rest.", "你有等同聖武士等級五倍的治療池。觸碰生物來恢復生命值，或花 5 點治癒一種疾病或毒素。長休後補滿。"],
  ["divine-smite", "When you hit with a melee weapon attack, spend a spell slot to deal extra radiant damage: 2d8, plus 1d8 per slot level above 1st (up to 5d8), and 1d8 more against undead or fiends.", "近戰武器命中時，消耗一個法術位造成額外光耀傷害：2d8，每高於 1 環多 1d8（上限 5d8），對不死生物或邪魔再多 1d8。"],
  ["improved-divine-smite", "Every melee weapon hit deals an extra 1d8 radiant damage.", "每次近戰武器命中都額外造成 1d8 光耀傷害。"],
  ["divine-health", "You are immune to disease.", "你免疫疾病。"],
  ["aura-of-protection", "You and friendly creatures within 10 feet add your Charisma modifier to saving throws while you are conscious.", "你清醒時，你與 10 呎內友方的豁免加上你的魅力調整值。"],
  ["aura-of-courage", "You and friendly creatures within 10 feet cannot be frightened while you are conscious.", "你清醒時，你與 10 呎內友方不會陷入恐慌。"],
  ["aura-of-devotion", "You and friendly creatures within 10 feet cannot be charmed while you are conscious.", "你清醒時，你與 10 呎內友方不會被魅惑。"],
  ["cleansing-touch", "Action: end a spell on yourself or on a willing creature you touch. Uses depend on your Charisma modifier.", "動作：結束你自己或你觸碰的自願生物身上的一個法術。次數取決於魅力調整值。"],
  ["purity-of-heart", "You are always under the effect of a protection from evil and good.", "你持續受到「防護善惡」的效果保護。"],
  ["oath-of-devotion", "Your Sacred Oath: the honest, noble knight. It brings Sacred Weapon, Turn the Unholy and Aura of Devotion.", "你的神聖誓約：誠實高尚的騎士。帶來神聖武器、驅逐不潔與奉獻光環。"],
  ["holy-nimbus", "Action: for a minute you shine with bright light in 30 feet and enemies that start their turn there take radiant damage. Once per long rest.", "動作：一分鐘內你散發 30 呎的明亮光芒，在其中開始回合的敵人受到光耀傷害。每次長休一次。"],

  // Ranger
  ["favored-enemy", "You are skilled at tracking and recalling facts about your chosen kind of enemy, and you know their language.", "你擅長追蹤並回想你選定的敵人種類的資訊，也懂得他們的語言。"],
  ["natural-explorer", "In your favored terrain, travel is not slowed by difficult terrain and you are harder to lose your way.", "在偏好地形中，困難地形不會拖慢旅程，也不容易迷路。"],
  ["hunter", "Colossus Slayer: once per turn, a weapon hit deals an extra 1d8 damage to a creature that is already below its hit point maximum.", "巨獸殺手：每回合一次，武器命中已受傷的生物時額外造成 1d8 傷害。"],
  ["hunter-multiattack", "Multiattack: you can strike every creature near your target, or every creature that is within 5 feet of you.", "多重攻擊：可攻擊目標附近的所有生物，或你 5 呎內的所有生物。"],
  ["rangers-lands-stride", "You move through nonmagical difficult terrain without extra cost.", "穿過非魔法的困難地形不需額外移動力。"],
  ["defensive-tactics", "Choose a way to stand against a threat: escape the horde, defend against many attackers, or keep your will steady.", "選擇面對威脅的方式：脫離群敵、抵禦多名攻擊者，或穩住意志。"],
  ["superior-hunters-defense", "Reaction: when you take damage, gain resistance to that damage type until the end of the turn.", "反應：受到傷害時，到回合結束前獲得該傷害類型的抗性。"],
  ["vanish", "You can Hide as a bonus action, and you cannot be tracked by nonmagical means unless you choose to leave a trail.", "你可以用附贈動作躲藏，除非你願意留下痕跡，否則無法被非魔法手段追蹤。"],
  ["feral-senses", "You do not suffer disadvantage attacking creatures you cannot see, and you know where invisible creatures within 30 feet are.", "攻擊看不見的生物不會有劣勢，並知道 30 呎內隱形生物的位置。"],
  ["foe-slayer", "Once per turn, add your Wisdom modifier to the attack roll or damage roll against one of your favored enemies.", "每回合一次，對你的偏好敵人進行攻擊骰或傷害骰時，加上感知調整值。"],

  // Rogue
  ["sneak-attack", "Once per turn, deal extra damage with a finesse or ranged weapon if you have advantage, or an ally stands within 5 feet of the target and you do not have disadvantage. The dice grow as you level.", "每回合一次，使用靈巧或遠程武器時，若你有優勢，或目標 5 呎內有你的盟友且你沒有劣勢，就造成額外傷害。傷害骰隨等級增加。"],
  ["thieves-cant", "You know thieves' cant, a secret mix of dialect and code, and its signs.", "你懂得盜賊黑話，一種混合方言與暗號的祕密語言及其手勢。"],
  ["cunning-action", "On your turn you can Dash, Disengage or Hide as a bonus action.", "你的回合中，可用附贈動作疾走、脫離或躲藏。"],
  ["uncanny-dodge", "Reaction: halve the damage from an attacker you can see that hits you.", "反應：把你看得見的攻擊者命中你的傷害減半。"],
  ["reliable-talent", "When you make an ability check you are proficient in, a d20 roll of 9 or lower counts as a 10.", "進行你熟練的屬性檢定時，d20 結果 9 或以下視為 10。"],
  ["blindsense", "If you can hear, you know where any hidden or invisible creature within 10 feet is.", "只要聽得見，你就知道 10 呎內隱藏或隱形生物的位置。"],
  ["slippery-mind", "You are proficient in Wisdom saving throws.", "你熟練感知豁免。"],
  ["elusive", "No attack roll has advantage against you while you are not incapacitated.", "只要你沒有失能，對你的攻擊骰都不會有優勢。"],
  ["stroke-of-luck", "Turn a missed attack into a hit, or a failed ability check into a 20. It comes back on a short or long rest.", "把一次未命中的攻擊變成命中，或把失敗的屬性檢定變成 20。短休或長休後恢復。"],
  ["thief", "Your Roguish Archetype: quick hands and a talent for climbing, jumping and using magic items.", "你的盜賊類型：手腳俐落，擅長攀爬、跳躍與使用魔法物品。"],
  ["fast-hands", "Cunning Action also lets you make a Sleight of Hand check, disarm a trap, open a lock, or use an object.", "狡詐動作也可用來進行巧手檢定、拆除陷阱、開鎖或使用物件。"],
  ["second-story-work", "You climb at your full walking speed, and your running jump goes further by your Dexterity modifier.", "攀爬速度等同步行速度，助跑跳躍距離增加敏捷調整值。"],
  ["supreme-sneak", "You have advantage on Stealth checks if you move no more than half your speed.", "移動不超過一半速度時，隱匿檢定具有優勢。"],
  ["use-magic-device", "You ignore class, race and level requirements for using magic items.", "使用魔法物品時，無視職業、種族與等級限制。"],
  ["thiefs-reflexes", "You take two turns during the first round of a fight, the second at initiative minus 10.", "戰鬥第一輪中你會行動兩次，第二次在先攻值減 10 時。"],
  ["beast-speech", "Invocation: cast speak with animals at will, without a spell slot.", "祕法祈請：可隨意施放「與動物交談」，不耗法術位。"],
  ["mask-of-many-faces", "Invocation: cast disguise self at will, without a spell slot.", "祕法祈請：可隨意施放「易容術」，不耗法術位。"],
  ["hide-in-plain-sight", "Spend a minute building camouflage against a solid surface: you gain +10 to Stealth checks while you stay still.", "花一分鐘靠著堅硬表面偽裝：只要保持不動，隱匿檢定 +10。"],
  ["tranquility", "At the end of a long rest you gain the effect of a sanctuary spell that lasts until your next long rest, or until you attack or cast a spell.", "長休結束時，你獲得持續到下次長休的「庇護所」效果；你攻擊或施放法術時結束。"],
  ["thief-of-five-fates", "Invocation: cast bane once using a warlock spell slot. It comes back on a long rest.", "祕法祈請：使用邪術師法術位施放「災禍術」一次。長休後恢復。"],

  // Sorcerer
  ["font-of-magic", "You have sorcery points equal to your level. Spend them to create spell slots or turn slots back into points. They come back on a long rest.", "你有等同等級的術法點，可用來創造法術位，或把法術位換回術法點。長休後恢復。"],
  ["create-slot-1", "Spend 2 sorcery points to create a 1st-level spell slot.", "花 2 點術法點創造一個 1 環法術位。"],
  ["create-slot-2", "Spend 3 sorcery points to create a 2nd-level spell slot.", "花 3 點術法點創造一個 2 環法術位。"],
  ["create-slot-3", "Spend 5 sorcery points to create a 3rd-level spell slot.", "花 5 點術法點創造一個 3 環法術位。"],
  ["create-slot-4", "Spend 6 sorcery points to create a 4th-level spell slot.", "花 6 點術法點創造一個 4 環法術位。"],
  ["create-slot-5", "Spend 7 sorcery points to create a 5th-level spell slot.", "花 7 點術法點創造一個 5 環法術位。"],
  ["slot-to-points-1", "Give up a 1st-level slot to gain 1 sorcery point.", "放棄一個 1 環法術位，換得 1 點術法點。"],
  ["slot-to-points-2", "Give up a 2nd-level slot to gain 2 sorcery points.", "放棄一個 2 環法術位，換得 2 點術法點。"],
  ["slot-to-points-3", "Give up a 3rd-level slot to gain 3 sorcery points.", "放棄一個 3 環法術位，換得 3 點術法點。"],
  ["slot-to-points-4", "Give up a 4th-level slot to gain 4 sorcery points.", "放棄一個 4 環法術位，換得 4 點術法點。"],
  ["slot-to-points-5", "Give up a 5th-level slot to gain 5 sorcery points.", "放棄一個 5 環法術位，換得 5 點術法點。"],
  ["metamagic", "You twist your spells with sorcery points. You know two Metamagic options and can add more as you level.", "你用術法點扭轉法術。你掌握兩種超魔，之後隨等級增加。"],
  ["metamagic-additional", "You learn additional Metamagic options.", "你學會更多的超魔選項。"],
  ["careful-spell", "Spend 1 sorcery point so chosen creatures automatically succeed on their saving throw against your spell.", "花 1 點術法點，讓你指定的生物自動通過對你法術的豁免。"],
  ["empowered-spell", "Spend 1 sorcery point to reroll some of your spell's damage dice and keep the new rolls.", "花 1 點術法點，重擲部分法術傷害骰並採用新結果。"],
  ["extended-spell", "Spend 1 sorcery point to double the duration of a spell that lasts a minute or more.", "花 1 點術法點，把持續一分鐘以上的法術時間加倍。"],
  ["heightened-spell", "Spend 3 sorcery points to give one target disadvantage on its first save against the spell.", "花 3 點術法點，讓一個目標對該法術的第一次豁免具有劣勢。"],
  ["quickened-spell", "Spend 2 sorcery points to cast a spell that takes an action as a bonus action instead.", "花 2 點術法點，把原本需要動作的法術改以附贈動作施放。"],
  ["subtle-spell", "Spend 1 sorcery point to cast a spell without verbal or somatic parts.", "花 1 點術法點，施放法術時不需要言語或姿勢成分。"],
  ["twinned-spell", "Spend sorcery points equal to the spell's level to target a second creature with a single-target spell.", "花費等同法術環級的術法點，讓單一目標法術多指定一個目標。"],
  ["sorcerous-restoration", "On a short rest you regain 4 expended sorcery points.", "短休時恢復 4 點已消耗的術法點。"],
  ["draconic-bloodline", "Your sorcerous origin. Your hit points rise by 1 per level, and without armor your Armor Class is 13 plus your Dexterity modifier.", "你的術法根源。每級生命值多 1 點，未著甲時護甲等級為 13 加上敏捷調整值。"],
  ["elemental-affinity", "Add your Charisma modifier to damage of your dragon ancestry's type. Spend 1 sorcery point to resist that type for an hour.", "你的龍族血脈所屬類型的傷害加上魅力調整值；花 1 點術法點可在一小時內抵抗該類型。"],
  ["dragon-wings", "Bonus action: sprout wings and fly at your walking speed until you dismiss them. Once per long rest.", "附贈動作：長出翅膀，以步行速度飛行，直到你收起。每次長休一次。"],
  ["draconic-presence", "Spend 5 sorcery points to project an aura of awe or fear for a minute, charming or frightening creatures that fail a Wisdom save.", "花 5 點術法點，一分鐘內散發敬畏或恐懼的氣場，感知豁免失敗的生物會被魅惑或恐慌。"],

  // Warlock
  ["fiend-patron", "Your otherworldly patron is a fiend. It grants you spells and boons that burn with hellfire.", "你的異界贊助者是邪魔，賜予你燃燒著地獄烈焰的法術與恩賜。"],
  ["dark-ones-blessing", "When you reduce a hostile creature to 0 hit points, you gain temporary hit points: your Charisma modifier plus warlock level.", "把敵對生物打到 0 點生命值時，獲得等同魅力調整值加上邪術師等級的臨時生命值。"],
  ["dark-ones-own-luck", "Add a d10 to an ability check or saving throw after seeing the roll. It comes back on a short or long rest.", "看見擲骰結果後，在屬性檢定或豁免上加 1d10。短休或長休後恢復。"],
  ["fiendish-resilience", "After a rest, choose one damage type to resist until you choose another.", "休息後選擇一種傷害類型作為抗性，直到你改選另一種。"],
  ["hurl-through-hell", "When you hit a creature, banish it through the lower planes; it returns taking heavy psychic damage. Once per long rest.", "命中生物時，把它放逐穿越下層位面；返回時受到大量心靈傷害。每次長休一次。"],
  ["eldritch-invocations", "Fragments of forbidden knowledge that shape your power. You choose a number of them as you level.", "形塑你力量的禁忌知識碎片，隨等級可選擇更多個。"],
  ["pact-boon", "A gift from your patron, chosen at 3rd level: a chain, a blade or a tome.", "贊助者在 3 級賜予的恩賜：鎖鏈、利刃或書卷。"],
  ["pact-of-the-chain", "You learn find familiar and your familiar can take special forms.", "你學會「尋獲魔寵」，且你的魔寵能變成特殊形態。"],
  ["pact-of-the-blade", "Action: summon a pact weapon in your hand, which counts as magical and which you are proficient with.", "動作：在手中召喚契約武器，視為魔法武器且你熟練使用。"],
  ["pact-of-the-tome", "Your patron gives you a Book of Shadows with extra cantrips.", "贊助者賜予你一本暗影之書，內含額外戲法。"],
  ["agonizing-blast", "Add your Charisma modifier to the damage of your eldritch blast.", "魔能爆的傷害加上魅力調整值。"],
  ["repelling-blast", "A creature hit by your eldritch blast is pushed up to 10 feet away.", "被魔能爆命中的生物會被推開至多 10 呎。"],
  ["devils-sight", "You see normally in darkness, magical or not, to a distance of 120 feet.", "你在 120 呎內於黑暗中（含魔法黑暗）也能正常視物。"],
  ["armor-of-shadows", "You can cast mage armor on yourself at will, without a spell slot.", "你可隨意對自己施放「法師護甲」，不耗法術位。"],
  ["eldritch-sight", "You can cast detect magic at will, without a spell slot.", "你可隨意施放「偵測魔法」，不耗法術位。"],
  ["misty-visions", "You can cast silent image at will, without a spell slot.", "你可隨意施放「無聲幻影」，不耗法術位。"],
  ["fiendish-vigor", "You can cast false life on yourself at will, at its lowest level.", "你可隨意以最低環位對自己施放「虛假生命」。"],
  ["mystic-arcanum-6", "Choose a 6th-level warlock spell. You can cast it once per long rest without a slot.", "選擇一個 6 環邪術師法術，每次長休可免耗法術位施放一次。"],
  ["mystic-arcanum-7", "Choose a 7th-level warlock spell. You can cast it once per long rest without a slot.", "選擇一個 7 環邪術師法術，每次長休可免耗法術位施放一次。"],
  ["mystic-arcanum-8", "Choose an 8th-level warlock spell. You can cast it once per long rest without a slot.", "選擇一個 8 環邪術師法術，每次長休可免耗法術位施放一次。"],
  ["mystic-arcanum-9", "Choose a 9th-level warlock spell. You can cast it once per long rest without a slot.", "選擇一個 9 環邪術師法術，每次長休可免耗法術位施放一次。"],
  ["eldritch-master", "Spend a minute entreating your patron to regain all your expended Pact Magic slots. Once per long rest.", "花一分鐘向贊助者祈求，恢復所有已消耗的契約魔法法術位。每次長休一次。"],

  // Wizard
  ["arcane-recovery", "Once a day after a short rest, regain spell slots whose levels add up to half your wizard level (rounded up), none higher than 5th.", "每日一次，短休後恢復環級總和不超過巫師等級一半（向上取整）的法術位，單一環級不超過 5。"],
  ["school-of-evocation", "Your Arcane Tradition: you shape destructive magic to spare your friends and push your cantrips and evocations further.", "你的奧術傳承：塑造破壞性魔法並保護友軍，讓戲法與塑能法術更具威力。"],
  ["sculpt-spells", "When you cast an evocation spell that affects others you can see, choose some to automatically succeed on their save and take no damage.", "施放影響你看得見的其他生物的塑能法術時，可指定部分生物自動通過豁免且不受傷。"],
  ["potent-cantrip", "When a creature succeeds on a save against your cantrip, it still takes half the damage.", "生物通過你戲法的豁免時，仍會承受一半傷害。"],
  ["empowered-evocation", "Add your Intelligence modifier to the damage of any wizard evocation spell you cast.", "你施放的任何巫師塑能法術，傷害加上智力調整值。"],
  ["overchannel", "Deal the maximum damage with a wizard spell of 5th level or lower. Using it again before a long rest hurts you.", "5 環以下的巫師法術造成最大傷害。長休前再次使用會讓你自己受傷。"],
  ["spell-mastery", "Choose a 1st-level and a 2nd-level wizard spell. You can cast them at their lowest level without a slot.", "選擇一個 1 環與一個 2 環巫師法術，可免耗法術位以最低環位施放。"],
  ["signature-spells", "Choose two 3rd-level wizard spells. They are always prepared, and you can cast each once at 3rd level without a slot per short rest.", "選擇兩個 3 環巫師法術，它們永遠視為已準備；每次短休可各免耗法術位以 3 環施放一次。"],
];

const byId = new Map(entries.map(([id, en, zh]) => [id, { en, zh }]));

// The description of a feature (by its id, with or without "feature:") in the page's language, or null when none is written.
export function featureText(id, language) {
  const entry = byId.get(id.replace(/^feature:/, ""));
  if (entry === undefined) return null;
  return language === "zh-TW" ? entry.zh : entry.en;
}

// Every feature id with a description, for the test that checks the whole catalogue is covered.
export const describedFeatures = [...byId.keys()];
