// What the Activity page knows right now, shared by its parts. A part changes it by assigning to a field.
export const app = {
  sessionToken: null,
  picker: null,
  applicationId: null,
  pollErrorShown: false,
  discordSdk: null,
  currentGameId: null,
  tableTimer: null,
  loadingTable: false,
  tableRefreshFailures: 0,
  lastTableRefreshAt: 0,
  tableToken: null,
  lastFullTableAt: 0,
  currentSnapshot: null,
  connectionStage: "Discord connection",
  discordConnected: false,
  lastRollPromptId: null,
  rollingCheck: false,
  uiLanguage: "en",
  discordLanguage: "en",
  activityStrings: {},
  selectedPartyCharacterId: null,
  selectedWorkspaceTab: "actions",
  selectedEnemyName: null,
  mapScale: 1,
  mapIdentity: "",
  mapBaseSize: null,
  mapOffset: { x: 0, y: 0 },
  classNames: {},
  lastGameSignature: "",
  moveCountdown: null,
  movePainted: "",
  activeMoveKey: null,
  focusBeforeVote: null,
  mapPick: false,
  mapDrag: null,
  pinchStart: null,
  suppressMapClick: false,
  selectedActionCategory: null,
  actionDraftSubmissionKey: null,
  actionsSignature: "",
  actionInFlight: false,
  rollsPrimed: false,
  rollToastTimer: 0,
};
