// What the Activity page knows right now, shared by its parts. A part changes it by assigning to a field.
export const app = {
  sessionToken: null,
  picker: null,
  applicationId: null,
  pollErrorShown: false,
  discordSdk: null,
  currentGameId: null,
  tableTimer: null,
  loadingTable: false,
  tableRefreshFailures: 0,
  lastTableRefreshAt: 0,
  tableToken: null,
  lastFullTableAt: 0,
  currentSnapshot: null,
  connectionStage: "Discord connection",
  discordConnected: false,
  lastRollPromptId: null,
  rollingCheck: false,
  uiLanguage: "en",
  discordLanguage: "en",
  activityStrings: {},
  selectedPartyCharacterId: null,
  selectedWorkspaceTab: "actions",
  selectedEnemyName: null,
  mapScale: 1,
  mapIdentity: "",
  mapBaseSize: null,
  mapOffset: { x: 0, y: 0 },
  classNames: {},
  lastGameSignature: "",
  moveCountdown: null,
  movePainted: "",
  activeMoveKey: null,
  focusBeforeVote: null,
  mapPick: false,
  mapDrag: null,
  pinchStart: null,
  suppressMapClick: false,
  selectedActionCategory: null,
  actionDraftSubmissionKey: null,
  actionsSignature: "",
  actionInFlight: false,
  // The label of the button last pressed, so the pill can say what was done.
  pressedLabel: null,
  // The panels at the screen's edges: which ones the table opened by itself, whether it was your turn at the last paint, how many story lines came while the story was shut, and the language the story was last worded in.
  drawerAuto: { left: false, bottom: false, right: false },
  wasMyTurn: false,
  unreadStory: 0,
  drawerLanguage: null,
  rollsPrimed: false,
  rollToastTimer: 0,
};
